// We are modularizing this manually because the current modularize setting in Emscripten has some issues:
// https://github.com/kripken/emscripten/issues/5820
var Module = (function(Module) {
  
    // If Module already exists, use it
    var Module = typeof Module !== 'undefined' ? Module : {};
    
    Module['preRunHasRun'] = new Promise(function(resolve){
      // TODO: Add on to any postRun objects already there
      Module['preRun'] = function(){
        // When Emscripted calls preRun, this resolves
        resolve();
      }
    }.bind(this));
    
    var postRunHasRun = Module['postRunHasRun'] = new Promise(function(resolve){
      // TODO: Add on to any postRun objects already there
      Module['postRun'] = function(){
        // When Emscripted calls postRun, this resolves
        resolve();
      }
    }.bind(this));
    
    // This is a promise that a module loader can listen for 
    Module['ready'] = new Promise(function(resolve, reject){
      // TODO: Add on to any onAbort function already there
      Module['onAbort'] = function(what){
        reject(new Error(what));
      }
  
      return postRunHasRun.then(function(){
        resolve(Module);
      }.bind(this));
  
    }.bind(this));

var f;f||(f=typeof Module !== 'undefined' ? Module : {});
f.preRunHasRun.then(function(){var a;var b=h(4);var c={};var d=function(){function a(a,b){this.j=a;this.db=b;this.C=1;this.ba=[]}a.prototype.bind=function(a){if(!this.j)throw"Statement closed";this.reset();return Array.isArray(a)?this.Ia(a):this.Ja(a)};a.prototype.step=function(){var a;if(!this.j)throw"Statement closed";this.C=1;switch(a=fc(this.j)){case c.Ca:return!0;case c.DONE:return!1;default:return this.db.handleError(a)}};a.prototype.Qa=function(a){null==a&&(a=this.C++);return hc(this.j,a)};
a.prototype.Ra=function(a){null==a&&(a=this.C++);return ic(this.j,a)};a.prototype.getBlob=function(a){var b;null==a&&(a=this.C++);var c=jc(this.j,a);var d=kc(this.j,a);var e=new Uint8Array(c);for(a=b=0;0<=c?b<c:b>c;a=0<=c?++b:--b)e[a]=k[d+a];return e};a.prototype.get=function(a){var b,d;null!=a&&this.bind(a)&&this.step();var e=[];a=b=0;for(d=vb(this.j);0<=d?b<d:b>d;a=0<=d?++b:--b)switch(lc(this.j,a)){case c.Ba:case c.FLOAT:e.push(this.Qa(a));break;case c.Da:e.push(this.Ra(a));break;case c.ya:e.push(this.getBlob(a));
break;default:e.push(null)}return e};a.prototype.getColumnNames=function(){var a,b;var c=[];var d=a=0;for(b=vb(this.j);0<=b?a<b:a>b;d=0<=b?++a:--a)c.push(mc(this.j,d));return c};a.prototype.getAsObject=function(a){var b,c;var d=this.get(a);var e=this.getColumnNames();var g={};a=b=0;for(c=e.length;b<c;a=++b){var l=e[a];g[l]=d[a]}return g};a.prototype.run=function(a){null!=a&&this.bind(a);this.step();return this.reset()};a.prototype.Ma=function(a,b){var c;null==b&&(b=this.C++);a=aa(a);this.ba.push(c=
ba(a,ca));this.db.handleError(O(this.j,b,c,a.length-1,0))};a.prototype.Ha=function(a,b){var c;null==b&&(b=this.C++);this.ba.push(c=ba(a,ca));this.db.handleError(Qa(this.j,b,c,a.length,0))};a.prototype.La=function(a,b){null==b&&(b=this.C++);this.db.handleError((a===(a|0)?Ra:wb)(this.j,b,a))};a.prototype.Ka=function(a){null==a&&(a=this.C++);Qa(this.j,a,0,0,0)};a.prototype.oa=function(a,b){null==b&&(b=this.C++);switch(typeof a){case "string":this.Ma(a,b);break;case "number":case "boolean":this.La(a+
0,b);break;case "object":if(null===a)this.Ka(b);else if(null!=a.length)this.Ha(a,b);else throw"Wrong API use : tried to bind a value of an unknown type ("+a+").";}};a.prototype.Ja=function(a){var b;for(b in a){var c=a[b];var d=nc(this.j,b);0!==d&&this.oa(c,d)}return!0};a.prototype.Ia=function(a){var b,c;var d=b=0;for(c=a.length;b<c;d=++b){var e=a[d];this.oa(e,d+1)}return!0};a.prototype.reset=function(){this.freemem();return oc(this.j)===c.V&&pc(this.j)===c.V};a.prototype.freemem=function(){for(var a;a=
this.ba.pop();)da(a);return null};a.prototype.free=function(){this.freemem();var a=qc(this.j)===c.V;delete this.db.Z[this.j];this.j=ka;return a};return a}();var e=function(){function a(a){this.filename="dbfile_"+(4294967295*Math.random()>>>0);if(null!=a){var c=this.filename,d=c?m("/",c):"/";c=ea(!0,!0);d=fa(d,(void 0!==c?c:438)&4095|32768,0);if(a){if("string"===typeof a){for(var e=Array(a.length),l=0,n=a.length;l<n;++l)e[l]=a.charCodeAt(l);a=e}ha(d,c|146);e=p(d,"w");ia(e,a,0,a.length,0,void 0);ja(e);
ha(d,c)}}this.handleError(g(this.filename,b));this.db=q(b,"i32");rc(this.db);this.Z={}}a.prototype.run=function(a,c){if(!this.db)throw"Database closed";c?(a=this.prepare(a,c),a.step(),a.free()):this.handleError(n(this.db,a,0,0,b));return this};a.prototype.exec=function(a){if(!this.db)throw"Database closed";var c=la();var e=ma(a)+1;var g=h(e);na(a,k,g,e);a=g;e=h(4);for(g=[];q(a,"i8")!==ka;){oa(b);oa(e);this.handleError(w(this.db,a,-1,b,e));var l=q(b,"i32");a=q(e,"i32");if(l!==ka){var n=new d(l,this);
for(l=null;n.step();)null===l&&(l={columns:n.getColumnNames(),values:[]},g.push(l)),l.values.push(n.get());n.free()}}pa(c);return g};a.prototype.each=function(a,b,c,d){"function"===typeof b&&(d=c,c=b,b=void 0);for(a=this.prepare(a,b);a.step();)c(a.getAsObject());a.free();if("function"===typeof d)return d()};a.prototype.prepare=function(a,c){oa(b);this.handleError(A(this.db,a,-1,b,ka));a=q(b,"i32");if(a===ka)throw"Nothing to prepare";var e=new d(a,this);null!=c&&e.bind(c);return this.Z[a]=e};a.prototype["export"]=
function(){var a;var c=this.Z;for(e in c){var d=c[e];d.free()}this.handleError(l(this.db));d=this.filename;var e=e={encoding:"binary"};e.flags=e.flags||"r";e.encoding=e.encoding||"binary";if("utf8"!==e.encoding&&"binary"!==e.encoding)throw Error('Invalid encoding type "'+e.encoding+'"');c=p(d,e.flags);d=qa(d).size;var n=new Uint8Array(d);ra(c,n,0,d,0);"utf8"===e.encoding?a=sa(n,0):"binary"===e.encoding&&(a=n);ja(c);this.handleError(g(this.filename,b));this.db=q(b,"i32");return a};a.prototype.close=
function(){var a;var b=this.Z;for(a in b){var c=b[a];c.free()}this.handleError(l(this.db));ta("/"+this.filename);return this.db=null};a.prototype.handleError=function(a){if(a===c.V)return null;a=sc(this.db);throw Error(a);};a.prototype.getRowsModified=function(){return v(this.db)};a.prototype.create_function=function(a,b){var d=ua(function(a,c,d){var e,g;var l=[];for(e=g=0;0<=c?g<c:g>c;e=0<=c?++g:--g){var n=q(d+4*e,"i32");var w=uc(n);e=function(){switch(!1){case 1!==w:return vc;case 2!==w:return wc;
case 3!==w:return xc;case 4!==w:return function(a){var b,c;var d=yc(a);var e=zc(a);a=new Uint8Array(d);for(b=c=0;0<=d?c<d:c>d;b=0<=d?++c:--c)a[b]=k[e+b];return a};default:return function(){return null}}}();e=e(n);l.push(e)}if(c=b.apply(null,l))switch(typeof c){case "number":return Ac(a,c);case "string":return Bc(a,c,-1,-1)}else return Cc(a)});this.handleError(Dc(this.db,a,b.length,c.Ea,0,d,0,0,0));return this};return a}();var g=f.cwrap("sqlite3_open","number",["string","number"]);var l=f.cwrap("sqlite3_close_v2",
"number",["number"]);var n=f.cwrap("sqlite3_exec","number",["number","string","number","number","number"]);f.cwrap("sqlite3_free","",["number"]);var v=f.cwrap("sqlite3_changes","number",["number"]);var A=f.cwrap("sqlite3_prepare_v2","number",["number","string","number","number","number"]);var w=f.cwrap("sqlite3_prepare_v2","number",["number","number","number","number","number"]);var O=f.cwrap("sqlite3_bind_text","number",["number","number","number","number","number"]);var Qa=f.cwrap("sqlite3_bind_blob",
"number",["number","number","number","number","number"]);var wb=f.cwrap("sqlite3_bind_double","number",["number","number","number"]);var Ra=f.cwrap("sqlite3_bind_int","number",["number","number","number"]);var nc=f.cwrap("sqlite3_bind_parameter_index","number",["number","string"]);var fc=f.cwrap("sqlite3_step","number",["number"]);var sc=f.cwrap("sqlite3_errmsg","string",["number"]);var vb=f.cwrap("sqlite3_data_count","number",["number"]);var hc=f.cwrap("sqlite3_column_double","number",["number",
"number"]);var ic=f.cwrap("sqlite3_column_text","string",["number","number"]);var kc=f.cwrap("sqlite3_column_blob","number",["number","number"]);var jc=f.cwrap("sqlite3_column_bytes","number",["number","number"]);var lc=f.cwrap("sqlite3_column_type","number",["number","number"]);var mc=f.cwrap("sqlite3_column_name","string",["number","number"]);var pc=f.cwrap("sqlite3_reset","number",["number"]);var oc=f.cwrap("sqlite3_clear_bindings","number",["number"]);var qc=f.cwrap("sqlite3_finalize","number",
["number"]);var Dc=f.cwrap("sqlite3_create_function_v2","number","number string number number number number number number number".split(" "));var uc=f.cwrap("sqlite3_value_type","number",["number"]);var yc=f.cwrap("sqlite3_value_bytes","number",["number"]);var xc=f.cwrap("sqlite3_value_text","string",["number"]);var vc=f.cwrap("sqlite3_value_int","number",["number"]);var zc=f.cwrap("sqlite3_value_blob","number",["number"]);var wc=f.cwrap("sqlite3_value_double","number",["number"]);var Ac=f.cwrap("sqlite3_result_double",
"",["number","number"]);var Cc=f.cwrap("sqlite3_result_null","",["number"]);var Bc=f.cwrap("sqlite3_result_text","",["number","string","number","number"]);var rc=f.cwrap("RegisterExtensionFunctions","number",["number"]);this.SQL={Database:e};for(a in this.SQL)f[a]=this.SQL[a];var ka=0;c.V=0;c.Pc=1;c.hd=2;c.sd=3;c.$a=4;c.bb=5;c.ld=6;c.NOMEM=7;c.vd=8;c.jd=9;c.kd=10;c.fb=11;c.NOTFOUND=12;c.gd=13;c.cb=14;c.td=15;c.EMPTY=16;c.wd=17;c.xd=18;c.eb=19;c.md=20;c.nd=21;c.od=22;c.ab=23;c.ed=24;c.ud=25;c.pd=26;
c.qd=27;c.yd=28;c.Ca=100;c.DONE=101;c.Ba=1;c.FLOAT=2;c.Da=3;c.ya=4;c.rd=5;c.Ea=1}.bind(this));var va={},r;for(r in f)f.hasOwnProperty(r)&&(va[r]=f[r]);f.arguments=[];f.thisProgram="./this.program";f.quit=function(a,b){throw b;};f.preRun=[];f.postRun=[];var wa=!1,t=!1,u=!1,xa=!1;wa="object"===typeof window;t="function"===typeof importScripts;u="object"===typeof process&&"function"===typeof require&&!wa&&!t;xa=!wa&&!u&&!t;var x="";function ya(a){return f.locateFile?f.locateFile(a,x):x+a}
if(u){x=__dirname+"/";var za,Aa;f.read=function(a,b){za||(za=require("fs"));Aa||(Aa=require("path"));a=Aa.normalize(a);a=za.readFileSync(a);return b?a:a.toString()};f.readBinary=function(a){a=f.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(f.thisProgram=process.argv[1].replace(/\\/g,"/"));f.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=f);process.on("uncaughtException",function(a){throw a;});process.on("unhandledRejection",
y);f.quit=function(a){process.exit(a)};f.inspect=function(){return"[Emscripten Module object]"}}else if(xa)"undefined"!=typeof read&&(f.read=function(a){return read(a)}),f.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?f.arguments=scriptArgs:"undefined"!=typeof arguments&&(f.arguments=arguments),"function"===typeof quit&&(f.quit=function(a){quit(a)});else if(wa||t)t?
x=self.location.href:document.currentScript&&(x=document.currentScript.src),x=0!==x.indexOf("blob:")?x.substr(0,x.lastIndexOf("/")+1):"",f.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},t&&(f.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),f.readAsync=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==
d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},f.setWindowTitle=function(a){document.title=a};var Ba=f.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),z=f.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||Ba);for(r in va)va.hasOwnProperty(r)&&(f[r]=va[r]);va=void 0;function Ca(a){var b=B;B=B+a+15&-16;return b}
function Da(a){var b=C[D>>2];a=b+a+15&-16;C[D>>2]=a;return a>=E&&!Ea()?(C[D>>2]=b,0):b}function Fa(a){var b;b||(b=16);return Math.ceil(a/b)*b}var Ga={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}},Ha=1,F=Array(64);function ua(a){for(var b=0;64>b;b++)if(!F[b])return F[b]=a,Ha+b;throw"Finished up all reserved function pointers. Use a higher value for RESERVED_FUNCTION_POINTERS.";}var Ia=!1;function assert(a,b){a||y("Assertion failed: "+b)}
function Ja(a){var b=f["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}var Ka={stackSave:function(){la()},stackRestore:function(){pa()},arrayToC:function(a){var b=h(a.length);k.set(a,b);return b},stringToC:function(a){var b=0;if(null!==a&&void 0!==a&&0!==a){var c=(a.length<<2)+1;b=h(c);na(a,G,b,c)}return b}},La={string:Ka.stringToC,array:Ka.arrayToC};
function oa(a){var b="i32";"*"===b.charAt(b.length-1)&&(b="i32");switch(b){case "i1":k[a>>0]=0;break;case "i8":k[a>>0]=0;break;case "i16":Ma[a>>1]=0;break;case "i32":C[a>>2]=0;break;case "i64":tempI64=[0,(tempDouble=0,1<=+Na(tempDouble)?0<tempDouble?(Oa(+Pa(tempDouble/4294967296),4294967295)|0)>>>0:~~+Sa((tempDouble-+(~~tempDouble>>>0))/4294967296)>>>0:0)];C[a>>2]=tempI64[0];C[a+4>>2]=tempI64[1];break;case "float":Ta[a>>2]=0;break;case "double":Ua[a>>3]=0;break;default:y("invalid type for setValue: "+
b)}}function q(a,b){b=b||"i8";"*"===b.charAt(b.length-1)&&(b="i32");switch(b){case "i1":return k[a>>0];case "i8":return k[a>>0];case "i16":return Ma[a>>1];case "i32":return C[a>>2];case "i64":return C[a>>2];case "float":return Ta[a>>2];case "double":return Ua[a>>3];default:y("invalid type for getValue: "+b)}return null}var ca=0,Va=2,Wa=4;
function ba(a,b){if("number"===typeof a){var c=!0;var d=a}else c=!1,d=a.length;b=b==Wa?e:["function"===typeof Xa?Xa:Ca,h,Ca,Da][void 0===b?Va:b](Math.max(d,1));if(c){var e=b;assert(0==(b&3));for(a=b+(d&-4);e<a;e+=4)C[e>>2]=0;for(a=b+d;e<a;)k[e++>>0]=0;return b}a.subarray||a.slice?G.set(a,b):G.set(new Uint8Array(a),b);return b}
function H(a){var b;if(0===b||!a)return"";for(var c=0,d,e=0;;){d=G[a+e>>0];c|=d;if(0==d&&!b)break;e++;if(b&&e==b)break}b||(b=e);d="";if(128>c){for(;0<b;)c=String.fromCharCode.apply(String,G.subarray(a,a+Math.min(b,1024))),d=d?d+c:c,a+=1024,b-=1024;return d}return sa(G,a)}var Ya="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function sa(a,b){for(var c=b;a[c];)++c;if(16<c-b&&a.subarray&&Ya)return Ya.decode(a.subarray(b,c));for(c="";;){var d=a[b++];if(!d)return c;if(d&128){var e=a[b++]&63;if(192==(d&224))c+=String.fromCharCode((d&31)<<6|e);else{var g=a[b++]&63;if(224==(d&240))d=(d&15)<<12|e<<6|g;else{var l=a[b++]&63;if(240==(d&248))d=(d&7)<<18|e<<12|g<<6|l;else{var n=a[b++]&63;if(248==(d&252))d=(d&3)<<24|e<<18|g<<12|l<<6|n;else{var v=a[b++]&63;d=(d&1)<<30|e<<24|g<<18|l<<12|n<<6|v}}}65536>d?c+=String.fromCharCode(d):(d-=
65536,c+=String.fromCharCode(55296|d>>10,56320|d&1023))}}else c+=String.fromCharCode(d)}}
function na(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var l=a.charCodeAt(g);if(55296<=l&&57343>=l){var n=a.charCodeAt(++g);l=65536+((l&1023)<<10)|n&1023}if(127>=l){if(c>=d)break;b[c++]=l}else{if(2047>=l){if(c+1>=d)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=d)break;b[c++]=224|l>>12}else{if(2097151>=l){if(c+3>=d)break;b[c++]=240|l>>18}else{if(67108863>=l){if(c+4>=d)break;b[c++]=248|l>>24}else{if(c+5>=d)break;b[c++]=252|l>>30;b[c++]=128|l>>24&63}b[c++]=128|l>>18&63}b[c++]=
128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-e}function ma(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:2097151>=d?b+4:67108863>=d?b+5:b+6}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function Za(a){return a.replace(/__Z[\w\d_]+/g,function(a){return a===a?a:a+" ["+a+"]"})}var $a=65536,ab=16777216,bb=16777216;
function cb(a,b){0<a%b&&(a+=b-a%b);return a}var buffer,k,G,Ma,C,Ta,Ua;function db(){f.HEAP8=k=new Int8Array(buffer);f.HEAP16=Ma=new Int16Array(buffer);f.HEAP32=C=new Int32Array(buffer);f.HEAPU8=G=new Uint8Array(buffer);f.HEAPU16=new Uint16Array(buffer);f.HEAPU32=new Uint32Array(buffer);f.HEAPF32=Ta=new Float32Array(buffer);f.HEAPF64=Ua=new Float64Array(buffer)}var eb,B,fb,gb,hb,ib,jb,D;eb=B=gb=hb=ib=jb=D=0;fb=!1;
f.reallocBuffer||(f.reallocBuffer=function(a){try{var b=k;var c=new ArrayBuffer(a);(new Int8Array(c)).set(b)}catch(d){return!1}return kb(c)?c:!1});function Ea(){var a=f.usingWasm?$a:ab,b=2147483648-a;if(C[D>>2]>b)return!1;var c=E;for(E=Math.max(E,bb);E<C[D>>2];)536870912>=E?E=cb(2*E,a):E=Math.min(cb((3*E+2147483648)/4,a),b);a=f.reallocBuffer(E);if(!a||a.byteLength!=E)return E=c,!1;f.buffer=buffer=a;db();return!0}var lb;
try{lb=Function.prototype.call.bind(Object.getOwnPropertyDescriptor(ArrayBuffer.prototype,"byteLength").get),lb(new ArrayBuffer(4))}catch(a){lb=function(b){return b.byteLength}}var mb=f.TOTAL_STACK||5242880,E=f.TOTAL_MEMORY||16777216;E<mb&&z("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+E+"! (TOTAL_STACK="+mb+")");
f.buffer?buffer=f.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(f.wasmMemory=new WebAssembly.Memory({initial:E/$a}),buffer=f.wasmMemory.buffer):buffer=new ArrayBuffer(E),f.buffer=buffer);db();function nb(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.Oa;"number"===typeof c?void 0===b.da?f.dynCall_v(c):f.dynCall_vi(c,b.da):c(void 0===b.da?null:b.da)}}}var ob=[],pb=[],qb=[],rb=[],sb=[],tb=!1;
function ub(){var a=f.preRun.shift();ob.unshift(a)}var Na=Math.abs,Sa=Math.ceil,Pa=Math.floor,Oa=Math.min,I=0,xb=null,yb=null;f.preloadedImages={};f.preloadedAudios={};function zb(a){return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}
(function(){function a(){try{if(f.wasmBinary)return new Uint8Array(f.wasmBinary);if(f.readBinary)return f.readBinary(e);throw"both async and sync fetching of the wasm failed";}catch(w){y(w)}}function b(){return f.wasmBinary||!wa&&!t||"function"!==typeof fetch?new Promise(function(b){b(a())}):fetch(e,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+e+"'";return a.arrayBuffer()}).catch(function(){return a()})}function c(a){function c(a){n=a.exports;
if(n.memory){a=n.memory;var b=f.buffer;a.byteLength<b.byteLength&&z("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");b=new Int8Array(b);(new Int8Array(a)).set(b);f.buffer=buffer=a;db()}f.asm=n;f.usingWasm=!0;I--;f.monitorRunDependencies&&f.monitorRunDependencies(I);0==I&&(null!==xb&&(clearInterval(xb),xb=null),yb&&(a=yb,yb=null,a()))}function d(a){c(a.instance)}function g(a){b().then(function(a){return WebAssembly.instantiate(a,l)}).then(a,
function(a){z("failed to asynchronously prepare wasm: "+a);y(a)})}if("object"!==typeof WebAssembly)return z("no native wasm support detected"),!1;if(!(f.wasmMemory instanceof WebAssembly.Memory))return z("no native wasm Memory in use"),!1;a.memory=f.wasmMemory;l.global={NaN:NaN,Infinity:Infinity};l["global.Math"]=Math;l.env=a;I++;f.monitorRunDependencies&&f.monitorRunDependencies(I);if(f.instantiateWasm)try{return f.instantiateWasm(l,c)}catch(Ra){return z("Module.instantiateWasm callback failed with error: "+
Ra),!1}f.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||zb(e)||"function"!==typeof fetch?g(d):WebAssembly.instantiateStreaming(fetch(e,{credentials:"same-origin"}),l).then(d,function(a){z("wasm streaming compile failed: "+a);z("falling back to ArrayBuffer instantiation");g(d)});return{}}var d="sql-wasm.wast",e="sql-wasm.wasm",g="sql-wasm.temp.asm.js";zb(d)||(d=ya(d));zb(e)||(e=ya(e));zb(g)||(g=ya(g));var l={global:null,env:null,asm2wasm:Ga,parent:f},n=null;f.asmPreload=f.asm;var v=
f.reallocBuffer;f.reallocBuffer=function(a){if("asmjs"===A)var b=v(a);else a:{a=cb(a,f.usingWasm?$a:ab);var c=f.buffer.byteLength;if(f.usingWasm)try{b=-1!==f.wasmMemory.grow((a-c)/65536)?f.buffer=f.wasmMemory.buffer:null;break a}catch(wb){b=null;break a}b=void 0}return b};var A="";f.asm=function(a,b){if(!b.table){a=f.wasmTableSize;void 0===a&&(a=1024);var d=f.wasmMaxTableSize;b.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==d?new WebAssembly.Table({initial:a,maximum:d,
element:"anyfunc"}):new WebAssembly.Table({initial:a,element:"anyfunc"}):Array(a);f.wasmTable=b.table}b.memoryBase||(b.memoryBase=f.STATIC_BASE);b.tableBase||(b.tableBase=0);b=c(b);assert(b,"no binaryen method succeeded.");return b}})();eb=1024;B=eb+49408;pb.push({Oa:function(){Ab()}});f.STATIC_BASE=eb;f.STATIC_BUMP=49408;B+=16;var J={};
function Bb(a){if(Bb.H){var b=C[a>>2];var c=C[b>>2]}else Bb.H=!0,J.USER=J.LOGNAME="web_user",J.PATH="/",J.PWD="/",J.HOME="/home/web_user",J.LANG="C.UTF-8",J._=f.thisProgram,c=fb?tb?Xa(1024):Da(1024):Ca(1024),b=fb?tb?Xa(256):Da(256):Ca(256),C[b>>2]=c,C[a>>2]=b;a=[];var d=0,e;for(e in J)if("string"===typeof J[e]){var g=e+"="+J[e];a.push(g);d+=g.length}if(1024<d)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");for(e=0;e<a.length;e++){d=g=a[e];for(var l=c,n=0;n<d.length;++n)k[l++>>0]=d.charCodeAt(n);
k[l>>0]=0;C[b+4*e>>2]=c;c+=g.length+1}C[b+4*a.length>>2]=0}
var K={B:1,A:2,Sc:3,Nb:4,R:5,ma:6,gb:7,lc:8,m:9,ub:10,ia:11,bd:11,ka:12,L:13,Gb:14,xc:15,M:16,ja:17,cd:18,S:19,T:20,N:21,h:22,fc:23,za:24,Cc:25,Zc:26,Hb:27,tc:28,U:29,Oc:30,Zb:31,Ic:32,Db:33,Aa:34,pc:42,Kb:43,vb:44,Qb:45,Rb:46,Sb:47,Yb:48,$c:49,jc:50,Pb:51,Ab:35,mc:37,mb:52,pb:53,dd:54,hc:55,qb:56,rb:57,Bb:35,sb:59,vc:60,kc:61,Wc:62,uc:63,qc:64,rc:65,Nc:66,nc:67,jb:68,Tc:69,wb:70,Jc:71,ac:72,Eb:73,ob:74,Dc:76,nb:77,Mc:78,Tb:79,Ub:80,Xb:81,Wb:82,Vb:83,wc:38,la:39,bc:36,$:40,Ec:95,Hc:96,zb:104,ic:105,
kb:97,Lc:91,Ac:88,sc:92,Qc:108,yb:111,hb:98,xb:103,ec:101,cc:100,Xc:110,Ib:112,Jb:113,Mb:115,lb:114,Cb:89,$b:90,Kc:93,Rc:94,ib:99,dc:102,Ob:106,yc:107,Yc:109,ad:87,Fb:122,Uc:116,Bc:95,oc:123,Lb:84,Fc:75,tb:125,zc:131,Gc:130,Vc:86},Cb={0:"Success",1:"Not super-user",2:"No such file or directory",3:"No such process",4:"Interrupted system call",5:"I/O error",6:"No such device or address",7:"Arg list too long",8:"Exec format error",9:"Bad file number",10:"No children",11:"No more processes",12:"Not enough core",
13:"Permission denied",14:"Bad address",15:"Block device required",16:"Mount device busy",17:"File exists",18:"Cross-device link",19:"No such device",20:"Not a directory",21:"Is a directory",22:"Invalid argument",23:"Too many open files in system",24:"Too many open files",25:"Not a typewriter",26:"Text file busy",27:"File too large",28:"No space left on device",29:"Illegal seek",30:"Read only file system",31:"Too many links",32:"Broken pipe",33:"Math arg out of domain of func",34:"Math result not representable",
35:"File locking deadlock error",36:"File or path name too long",37:"No record locks available",38:"Function not implemented",39:"Directory not empty",40:"Too many symbolic links",42:"No message of desired type",43:"Identifier removed",44:"Channel number out of range",45:"Level 2 not synchronized",46:"Level 3 halted",47:"Level 3 reset",48:"Link number out of range",49:"Protocol driver not attached",50:"No CSI structure available",51:"Level 2 halted",52:"Invalid exchange",53:"Invalid request descriptor",
54:"Exchange full",55:"No anode",56:"Invalid request code",57:"Invalid slot",59:"Bad font file fmt",60:"Device not a stream",61:"No data (for no delay io)",62:"Timer expired",63:"Out of streams resources",64:"Machine is not on the network",65:"Package not installed",66:"The object is remote",67:"The link has been severed",68:"Advertise error",69:"Srmount error",70:"Communication error on send",71:"Protocol error",72:"Multihop attempted",73:"Cross mount point (not really error)",74:"Trying to read unreadable message",
75:"Value too large for defined data type",76:"Given log. name not unique",77:"f.d. invalid for this operation",78:"Remote address changed",79:"Can   access a needed shared lib",80:"Accessing a corrupted shared lib",81:".lib section in a.out corrupted",82:"Attempting to link in too many libs",83:"Attempting to exec a shared library",84:"Illegal byte sequence",86:"Streams pipe error",87:"Too many users",88:"Socket operation on non-socket",89:"Destination address required",90:"Message too long",91:"Protocol wrong type for socket",
92:"Protocol not available",93:"Unknown protocol",94:"Socket type not supported",95:"Not supported",96:"Protocol family not supported",97:"Address family not supported by protocol family",98:"Address already in use",99:"Address not available",100:"Network interface is not configured",101:"Network is unreachable",102:"Connection reset by network",103:"Connection aborted",104:"Connection reset by peer",105:"No buffer space available",106:"Socket is already connected",107:"Socket is not connected",108:"Can't send after socket shutdown",
109:"Too many references",110:"Connection timed out",111:"Connection refused",112:"Host is down",113:"Host is unreachable",114:"Socket already connected",115:"Connection already in progress",116:"Stale file handle",122:"Quota exceeded",123:"No medium (in tape drive)",125:"Operation canceled",130:"Previous owner died",131:"State not recoverable"};function Db(a){f.___errno_location&&(C[f.___errno_location()>>2]=a);return a}
function Eb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function Fb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Eb(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function Gb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Hb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function Ib(){var a=Array.prototype.slice.call(arguments,0);return Fb(a.join("/"))}function m(a,b){return Fb(a+"/"+b)}
function Jb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Eb(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var Kb=[];function Lb(a,b){Kb[a]={input:[],output:[],K:b};Mb(a,Nb)}
var Nb={open:function(a){var b=Kb[a.node.rdev];if(!b)throw new L(K.S);a.tty=b;a.seekable=!1},close:function(a){a.tty.K.flush(a.tty)},flush:function(a){a.tty.K.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.K.va)throw new L(K.ma);for(var e=0,g=0;g<d;g++){try{var l=a.tty.K.va(a.tty)}catch(n){throw new L(K.R);}if(void 0===l&&0===e)throw new L(K.ia);if(null===l||void 0===l)break;e++;b[c+g]=l}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.K.ga)throw new L(K.ma);
for(var e=0;e<d;e++)try{a.tty.K.ga(a.tty,b[c+e])}catch(g){throw new L(K.R);}d&&(a.node.timestamp=Date.now());return e}},Ob={va:function(a){if(!a.input.length){var b=null;if(u){var c=new Buffer(256),d=0,e=process.stdin.fd;if("win32"!=process.platform){var g=!1;try{e=fs.openSync("/dev/stdin","r"),g=!0}catch(l){}}try{d=fs.readSync(e,c,0,256,null)}catch(l){if(-1!=l.toString().indexOf("EOF"))d=0;else throw l;}g&&fs.closeSync(e);0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&
"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=aa(b,!0)}return a.input.shift()},ga:function(a,b){null===b||10===b?(Ba(sa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(Ba(sa(a.output,0)),a.output=[])}},Pb={ga:function(a,b){null===b||10===b?(z(sa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<
a.output.length&&(z(sa(a.output,0)),a.output=[])}},M={v:null,o:function(){return M.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new L(K.B);M.v||(M.v={dir:{node:{u:M.c.u,l:M.c.l,lookup:M.c.lookup,O:M.c.O,rename:M.c.rename,unlink:M.c.unlink,rmdir:M.c.rmdir,readdir:M.c.readdir,symlink:M.c.symlink},stream:{D:M.f.D}},file:{node:{u:M.c.u,l:M.c.l},stream:{D:M.f.D,read:M.f.read,write:M.f.write,na:M.f.na,X:M.f.X,Y:M.f.Y}},link:{node:{u:M.c.u,l:M.c.l,
readlink:M.c.readlink},stream:{}},qa:{node:{u:M.c.u,l:M.c.l},stream:Qb}});c=Rb(a,b,c,d);N(c.mode)?(c.c=M.v.dir.node,c.f=M.v.dir.stream,c.b={}):32768===(c.mode&61440)?(c.c=M.v.file.node,c.f=M.v.file.stream,c.i=0,c.b=null):40960===(c.mode&61440)?(c.c=M.v.link.node,c.f=M.v.link.stream):8192===(c.mode&61440)&&(c.c=M.v.qa.node,c.f=M.v.qa.stream);c.timestamp=Date.now();a&&(a.b[b]=c);return c},Pa:function(a){if(a.b&&a.b.subarray){for(var b=[],c=0;c<a.i;++c)b.push(a.b[c]);return b}return a.b},zd:function(a){return a.b?
a.b.subarray?a.b.subarray(0,a.i):new Uint8Array(a.b):new Uint8Array},ra:function(a,b){a.b&&a.b.subarray&&b>a.b.length&&(a.b=M.Pa(a),a.i=a.b.length);if(!a.b||a.b.subarray){var c=a.b?a.b.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.b,a.b=new Uint8Array(b),0<a.i&&a.b.set(c.subarray(0,a.i),0))}else for(!a.b&&0<b&&(a.b=[]);a.b.length<b;)a.b.push(0)},Wa:function(a,b){if(a.i!=b)if(0==b)a.b=null,a.i=0;else{if(!a.b||a.b.subarray){var c=a.b;a.b=new Uint8Array(new ArrayBuffer(b));
c&&a.b.set(c.subarray(0,Math.min(b,a.i)))}else if(a.b||(a.b=[]),a.b.length>b)a.b.length=b;else for(;a.b.length<b;)a.b.push(0);a.i=b}},c:{u:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;N(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.i:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.F=4096;b.blocks=Math.ceil(b.size/b.F);return b},
l:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&M.Wa(a,b.size)},lookup:function(){throw Sb[K.A];},O:function(a,b,c,d){return M.createNode(a,b,c,d)},rename:function(a,b,c){if(N(a.mode)){try{var d=P(b,c)}catch(g){}if(d)for(var e in d.b)throw new L(K.la);}delete a.parent.b[a.name];a.name=c;b.b[c]=a;a.parent=b},unlink:function(a,b){delete a.b[b]},rmdir:function(a,b){var c=P(a,b),d;for(d in c.b)throw new L(K.la);delete a.b[b]},readdir:function(a){var b=
[".",".."],c;for(c in a.b)a.b.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=M.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new L(K.h);return a.link}},f:{read:function(a,b,c,d,e){var g=a.node.b;if(e>=a.node.i)return 0;a=Math.min(a.node.i-e,d);assert(0<=a);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){g=!1;if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&
(!a.b||a.b.subarray)){if(g)return a.b=b.subarray(c,c+d),a.i=d;if(0===a.i&&0===e)return a.b=new Uint8Array(b.subarray(c,c+d)),a.i=d;if(e+d<=a.i)return a.b.set(b.subarray(c,c+d),e),d}M.ra(a,e+d);if(a.b.subarray&&b.subarray)a.b.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.b[e+g]=b[c+g];a.i=Math.max(a.i,e+d);return d},D:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.i);if(0>b)throw new L(K.h);return b},na:function(a,b,c){M.ra(a.node,b+c);a.node.i=Math.max(a.node.i,
b+c)},X:function(a,b,c,d,e,g,l){if(32768!==(a.node.mode&61440))throw new L(K.S);c=a.node.b;if(l&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<e||e+d<a.node.i)c.subarray?c=c.subarray(e,e+d):c=Array.prototype.slice.call(c,e,e+d);a=!0;d=Xa(d);if(!d)throw new L(K.ka);b.set(c,d)}else a=!1,d=c.byteOffset;return{Va:d,aa:a}},Y:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new L(K.S);if(e&2)return 0;M.f.write(a,b,0,d,c,!1);return 0}}},Q={W:!1,Ya:function(){Q.W=!!process.platform.match(/^win/);var a=
process.binding("constants");a.fs&&(a=a.fs);Q.sa={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},pa:function(a){return Buffer.H?Buffer.from(a):new Buffer(a)},o:function(a){assert(u);return Q.createNode(null,"/",Q.ua(a.fa.root),0)},createNode:function(a,b,c){if(!N(c)&&32768!==(c&61440)&&40960!==(c&61440))throw new L(K.h);a=Rb(a,b,c);a.c=Q.c;a.f=Q.f;return a},ua:function(a){try{var b=fs.lstatSync(a);Q.W&&(b.mode=b.mode|(b.mode&292)>>2)}catch(c){if(!c.code)throw c;
throw new L(K[c.code]);}return b.mode},s:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.o.fa.root);b.reverse();return Ib.apply(null,b)},Na:function(a){a&=-2656257;var b=0,c;for(c in Q.sa)a&c&&(b|=Q.sa[c],a^=c);if(a)throw new L(K.h);return b},c:{u:function(a){a=Q.s(a);try{var b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new L(K[c.code]);}Q.W&&!b.F&&(b.F=4096);Q.W&&!b.blocks&&(b.blocks=(b.size+b.F-1)/b.F|0);return{dev:b.dev,ino:b.ino,mode:b.mode,nlink:b.nlink,uid:b.uid,
gid:b.gid,rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,F:b.F,blocks:b.blocks}},l:function(a,b){var c=Q.s(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&fs.truncateSync(c,b.size)}catch(d){if(!d.code)throw d;throw new L(K[d.code]);}},lookup:function(a,b){var c=m(Q.s(a),b);c=Q.ua(c);return Q.createNode(a,b,c)},O:function(a,b,c,d){a=Q.createNode(a,b,c,d);b=Q.s(a);try{N(a.mode)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,"",{mode:a.mode})}catch(e){if(!e.code)throw e;
throw new L(K[e.code]);}return a},rename:function(a,b,c){a=Q.s(a);b=m(Q.s(b),c);try{fs.renameSync(a,b)}catch(d){if(!d.code)throw d;throw new L(K[d.code]);}},unlink:function(a,b){a=m(Q.s(a),b);try{fs.unlinkSync(a)}catch(c){if(!c.code)throw c;throw new L(K[c.code]);}},rmdir:function(a,b){a=m(Q.s(a),b);try{fs.rmdirSync(a)}catch(c){if(!c.code)throw c;throw new L(K[c.code]);}},readdir:function(a){a=Q.s(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;throw new L(K[b.code]);}},symlink:function(a,
b,c){a=m(Q.s(a),b);try{fs.symlinkSync(c,a)}catch(d){if(!d.code)throw d;throw new L(K[d.code]);}},readlink:function(a){var b=Q.s(a);try{return b=fs.readlinkSync(b),b=Tb.relative(Tb.resolve(a.o.fa.root),b)}catch(c){if(!c.code)throw c;throw new L(K[c.code]);}}},f:{open:function(a){var b=Q.s(a.node);try{32768===(a.node.mode&61440)&&(a.P=fs.openSync(b,Q.Na(a.flags)))}catch(c){if(!c.code)throw c;throw new L(K[c.code]);}},close:function(a){try{32768===(a.node.mode&61440)&&a.P&&fs.closeSync(a.P)}catch(b){if(!b.code)throw b;
throw new L(K[b.code]);}},read:function(a,b,c,d,e){if(0===d)return 0;try{return fs.readSync(a.P,Q.pa(b.buffer),c,d,e)}catch(g){throw new L(K[g.code]);}},write:function(a,b,c,d,e){try{return fs.writeSync(a.P,Q.pa(b.buffer),c,d,e)}catch(g){throw new L(K[g.code]);}},D:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.node.mode&61440))try{b+=fs.fstatSync(a.P).size}catch(d){throw new L(K[d.code]);}if(0>b)throw new L(K.h);return b}}};B+=16;B+=16;B+=16;
var Ub=null,Vb={},R=[],Wb=1,S=null,Xb=!0,T={},L=null,Sb={};
function U(a,b){a=Jb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={ta:!0,ha:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.ha)throw new L(K.$);a=Eb(a.split("/").filter(function(a){return!!a}),!1);var e=Ub;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;e=P(e,a[d]);c=m(c,a[d]);e.I&&(!g||g&&b.ta)&&(e=e.I.root);if(!g||b.G)for(g=0;40960===(e.mode&61440);)if(e=Yb(c),c=Jb(Gb(c),e),e=U(c,{ha:b.ha}).node,40<g++)throw new L(K.$);}return{path:c,node:e}}
function Zb(a){for(var b;;){if(a===a.parent)return a=a.o.wa,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function $b(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%S.length}function ac(a){var b=$b(a.parent.id,a.name);a.J=S[b];S[b]=a}function bc(a){var b=$b(a.parent.id,a.name);if(S[b]===a)S[b]=a.J;else for(b=S[b];b;){if(b.J===a){b.J=a.J;break}b=b.J}}
function P(a,b){var c;if(c=(c=cc(a,"x"))?c:a.c.lookup?0:K.L)throw new L(c,a);for(c=S[$b(a.id,b)];c;c=c.J){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.c.lookup(a,b)}
function Rb(a,b,c,d){dc||(dc=function(a,b,c,d){a||(a=this);this.parent=a;this.o=a.o;this.I=null;this.id=Wb++;this.name=b;this.mode=c;this.c={};this.f={};this.rdev=d},dc.prototype={},Object.defineProperties(dc.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}}));a=new dc(a,b,c,d);ac(a);return a}function N(a){return 16384===(a&61440)}
var ec={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function tc(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function cc(a,b){if(Xb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return K.L}else return K.L;return 0}function Ec(a,b){try{return P(a,b),K.ja}catch(c){}return cc(a,"wx")}
function Fc(a,b,c){try{var d=P(a,b)}catch(e){return e.g}if(a=cc(a,"wx"))return a;if(c){if(!N(d.mode))return K.T;if(d===d.parent||"/"===Zb(d))return K.M}else if(N(d.mode))return K.N;return 0}function Gc(a){var b=4096;for(a=a||0;a<=b;a++)if(!R[a])return a;throw new L(K.za);}
function Hc(a,b){Ic||(Ic=function(){},Ic.prototype={},Object.defineProperties(Ic.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var c=new Ic,d;for(d in a)c[d]=a[d];a=c;b=Gc(b);a.fd=b;return R[b]=a}var Qb={open:function(a){a.f=Vb[a.node.rdev].f;a.f.open&&a.f.open(a)},D:function(){throw new L(K.U);}};function Mb(a,b){Vb[a]={f:b}}
function Jc(a,b){var c="/"===b,d=!b;if(c&&Ub)throw new L(K.M);if(!c&&!d){var e=U(b,{ta:!1});b=e.path;e=e.node;if(e.I)throw new L(K.M);if(!N(e.mode))throw new L(K.T);}b={type:a,fa:{},wa:b,Ua:[]};a=a.o(b);a.o=b;b.root=a;c?Ub=a:e&&(e.I=b,e.o&&e.o.Ua.push(b))}function fa(a,b,c){var d=U(a,{parent:!0}).node;a=Hb(a);if(!a||"."===a||".."===a)throw new L(K.h);var e=Ec(d,a);if(e)throw new L(e);if(!d.c.O)throw new L(K.B);return d.c.O(d,a,b,c)}function V(a,b){fa(a,(void 0!==b?b:511)&1023|16384,0)}
function Kc(a,b,c){"undefined"===typeof c&&(c=b,b=438);fa(a,b|8192,c)}function Lc(a,b){if(!Jb(a))throw new L(K.A);var c=U(b,{parent:!0}).node;if(!c)throw new L(K.A);b=Hb(b);var d=Ec(c,b);if(d)throw new L(d);if(!c.c.symlink)throw new L(K.B);c.c.symlink(c,b,a)}
function ta(a){var b=U(a,{parent:!0}).node,c=Hb(a),d=P(b,c),e=Fc(b,c,!1);if(e)throw new L(e);if(!b.c.unlink)throw new L(K.B);if(d.I)throw new L(K.M);try{T.willDeletePath&&T.willDeletePath(a)}catch(g){console.log("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+g.message)}b.c.unlink(b,c);bc(d);try{if(T.onDeletePath)T.onDeletePath(a)}catch(g){console.log("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+g.message)}}
function Yb(a){a=U(a).node;if(!a)throw new L(K.A);if(!a.c.readlink)throw new L(K.h);return Jb(Zb(a.parent),a.c.readlink(a))}function qa(a,b){a=U(a,{G:!b}).node;if(!a)throw new L(K.A);if(!a.c.u)throw new L(K.B);return a.c.u(a)}function Mc(a){return qa(a,!0)}function ha(a,b){var c;"string"===typeof a?c=U(a,{G:!0}).node:c=a;if(!c.c.l)throw new L(K.B);c.c.l(c,{mode:b&4095|c.mode&-4096,timestamp:Date.now()})}
function Nc(a){var b;"string"===typeof a?b=U(a,{G:!0}).node:b=a;if(!b.c.l)throw new L(K.B);b.c.l(b,{timestamp:Date.now()})}function Oc(a,b){if(0>b)throw new L(K.h);var c;"string"===typeof a?c=U(a,{G:!0}).node:c=a;if(!c.c.l)throw new L(K.B);if(N(c.mode))throw new L(K.N);if(32768!==(c.mode&61440))throw new L(K.h);if(a=cc(c,"w"))throw new L(a);c.c.l(c,{size:b,timestamp:Date.now()})}
function p(a,b,c,d){if(""===a)throw new L(K.A);if("string"===typeof b){var e=ec[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=Fb(a);try{g=U(a,{G:!(b&131072)}).node}catch(n){}}e=!1;if(b&64)if(g){if(b&128)throw new L(K.ja);}else g=fa(a,c,0),e=!0;if(!g)throw new L(K.A);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&!N(g.mode))throw new L(K.T);if(!e){var l=g?40960===(g.mode&61440)?K.$:N(g.mode)&&
("r"!==tc(b)||b&512)?K.N:cc(g,tc(b)):K.A;if(l)throw new L(l);}b&512&&Oc(g,0);b&=-641;c=Hc({node:g,path:Zb(g),flags:b,seekable:!0,position:0,f:g.f,Za:[],error:!1},d);c.f.open&&c.f.open(c);!f.logReadFiles||b&1||(Pc||(Pc={}),a in Pc||(Pc[a]=1,l("read file: "+a)));try{T.onOpenFile&&(l=0,1!==(b&2097155)&&(l|=1),0!==(b&2097155)&&(l|=2),T.onOpenFile(a,l))}catch(n){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+n.message)}return c}
function ja(a){if(null===a.fd)throw new L(K.m);a.ea&&(a.ea=null);try{a.f.close&&a.f.close(a)}catch(b){throw b;}finally{R[a.fd]=null}a.fd=null}function Qc(a,b,c){if(null===a.fd)throw new L(K.m);if(!a.seekable||!a.f.D)throw new L(K.U);a.position=a.f.D(a,b,c);a.Za=[]}
function ra(a,b,c,d,e){if(0>d||0>e)throw new L(K.h);if(null===a.fd)throw new L(K.m);if(1===(a.flags&2097155))throw new L(K.m);if(N(a.node.mode))throw new L(K.N);if(!a.f.read)throw new L(K.h);var g="undefined"!==typeof e;if(!g)e=a.position;else if(!a.seekable)throw new L(K.U);b=a.f.read(a,b,c,d,e);g||(a.position+=b);return b}
function ia(a,b,c,d,e,g){if(0>d||0>e)throw new L(K.h);if(null===a.fd)throw new L(K.m);if(0===(a.flags&2097155))throw new L(K.m);if(N(a.node.mode))throw new L(K.N);if(!a.f.write)throw new L(K.h);a.flags&1024&&Qc(a,0,2);var l="undefined"!==typeof e;if(!l)e=a.position;else if(!a.seekable)throw new L(K.U);b=a.f.write(a,b,c,d,e,g);l||(a.position+=b);try{if(a.path&&T.onWriteToFile)T.onWriteToFile(a.path)}catch(n){console.log("FS.trackingDelegate['onWriteToFile']('"+path+"') threw an exception: "+n.message)}return b}
function Rc(){L||(L=function(a,b){this.node=b;this.Xa=function(a){this.g=a;for(var b in K)if(K[b]===a){this.code=b;break}};this.Xa(a);this.message=Cb[a];this.stack&&Object.defineProperty(this,"stack",{value:Error().stack,writable:!0})},L.prototype=Error(),L.prototype.constructor=L,[K.A].forEach(function(a){Sb[a]=new L(a);Sb[a].stack="<generic error, no stack>"}))}var Sc;function ea(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Tc(a,b,c){a=m("/dev",a);var d=ea(!!b,!!c);Uc||(Uc=64);var e=Uc++<<8|0;Mb(e,{open:function(a){a.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(a,c,d,e){for(var g=0,l=0;l<e;l++){try{var n=b()}catch(Qa){throw new L(K.R);}if(void 0===n&&0===g)throw new L(K.ia);if(null===n||void 0===n)break;g++;c[d+l]=n}g&&(a.node.timestamp=Date.now());return g},write:function(a,b,d,e){for(var g=0;g<e;g++)try{c(b[d+g])}catch(w){throw new L(K.R);}e&&(a.node.timestamp=Date.now());
return g}});Kc(a,d,e)}var Uc,FS={},dc,Ic,Pc,Vc={};
function Wc(a,b,c){try{var d=a(b)}catch(e){if(e&&e.node&&Fb(b)!==Fb(Zb(e.node)))return-K.T;throw e;}C[c>>2]=d.dev;C[c+4>>2]=0;C[c+8>>2]=d.ino;C[c+12>>2]=d.mode;C[c+16>>2]=d.nlink;C[c+20>>2]=d.uid;C[c+24>>2]=d.gid;C[c+28>>2]=d.rdev;C[c+32>>2]=0;C[c+36>>2]=d.size;C[c+40>>2]=4096;C[c+44>>2]=d.blocks;C[c+48>>2]=d.atime.getTime()/1E3|0;C[c+52>>2]=0;C[c+56>>2]=d.mtime.getTime()/1E3|0;C[c+60>>2]=0;C[c+64>>2]=d.ctime.getTime()/1E3|0;C[c+68>>2]=0;C[c+72>>2]=d.ino;return 0}var W=0;
function X(){W+=4;return C[W-4>>2]}function Y(){return H(X())}function Xc(){var a=R[X()];if(!a)throw new L(K.m);return a}function Yc(a,b){W=b;return 0}function Zc(a){if(0===a)return 0;a=H(a);if(!J.hasOwnProperty(a))return 0;Zc.H&&da(Zc.H);a=J[a];var b=ma(a)+1,c=Xa(b);c&&na(a,k,c,b);Zc.H=c;return Zc.H}function $c(a){return Math.log(a)/Math.LN10}var Z=B;B+=48;ba(aa("GMT"),Va);
function ad(){function a(a){return(a=a.toTimeString().match(/\(([A-Za-z ]+)\)$/))?a[1]:"GMT"}if(!bd){bd=!0;C[cd()>>2]=60*(new Date).getTimezoneOffset();var b=new Date(2E3,0,1),c=new Date(2E3,6,1);C[dd()>>2]=Number(b.getTimezoneOffset()!=c.getTimezoneOffset());var d=a(b),e=a(c);d=ba(aa(d),ca);e=ba(aa(e),ca);c.getTimezoneOffset()<b.getTimezoneOffset()?(C[ed()>>2]=d,C[ed()+4>>2]=e):(C[ed()>>2]=e,C[ed()+4>>2]=d)}}var bd;
function fd(a){a/=1E3;if((wa||t)&&self.performance&&self.performance.now)for(var b=self.performance.now();self.performance.now()-b<a;);else for(b=Date.now();Date.now()-b<a;);return 0}f._usleep=fd;Rc();S=Array(4096);Jc(M,"/");V("/tmp");V("/home");V("/home/web_user");
(function(){V("/dev");Mb(259,{read:function(){return 0},write:function(a,b,e,g){return g}});Kc("/dev/null",259);Lb(1280,Ob);Lb(1536,Pb);Kc("/dev/tty",1280);Kc("/dev/tty1",1536);if("undefined"!==typeof crypto){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else u?b=function(){return require("crypto").randomBytes(1)[0]}:b=function(){y("random_device")};Tc("random",b);Tc("urandom",b);V("/dev/shm");V("/dev/shm/tmp")})();V("/proc");V("/proc/self");V("/proc/self/fd");
Jc({o:function(){var a=Rb("/proc/self","fd",16895,73);a.c={lookup:function(a,c){var b=R[+c];if(!b)throw new L(K.m);a={parent:null,o:{wa:"fake"},c:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");
pb.unshift(function(){if(!f.noFSInit&&!Sc){assert(!Sc,"FS.init was previously called. If you want to initialize later with custom parameters, remove any earlier calls (note that one is automatically added to the generated code)");Sc=!0;Rc();f.stdin=f.stdin;f.stdout=f.stdout;f.stderr=f.stderr;f.stdin?Tc("stdin",f.stdin):Lc("/dev/tty","/dev/stdin");f.stdout?Tc("stdout",null,f.stdout):Lc("/dev/tty","/dev/stdout");f.stderr?Tc("stderr",null,f.stderr):Lc("/dev/tty1","/dev/stderr");var a=p("/dev/stdin",
"r");assert(0===a.fd,"invalid handle for stdin ("+a.fd+")");a=p("/dev/stdout","w");assert(1===a.fd,"invalid handle for stdout ("+a.fd+")");a=p("/dev/stderr","w");assert(2===a.fd,"invalid handle for stderr ("+a.fd+")")}});qb.push(function(){Xb=!1});rb.push(function(){Sc=!1;var a=f._fflush;a&&a(0);for(a=0;a<R.length;a++){var b=R[a];b&&ja(b)}});pb.unshift(function(){});rb.push(function(){});if(u){var fs=require("fs"),Tb=require("path");Q.Ya()}D=Ca(4);gb=hb=Fa(B);ib=gb+mb;jb=Fa(ib);C[D>>2]=jb;fb=!0;
function aa(a,b){var c=Array(ma(a)+1);a=na(a,c,0,c.length);b&&(c.length=a);return c}f.wasmTableSize=2560;f.wasmMaxTableSize=2560;f.Fa={};
f.Ga={abort:y,enlargeMemory:Ea,getTotalMemory:function(){return E},abortOnCannotGrowMemory:function(){y("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+E+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")},jsCall_i:function(a){return F[a]()},jsCall_ii:function(a,b){return F[a](b)},jsCall_iii:function(a,
b,c){return F[a](b,c)},jsCall_iiii:function(a,b,c,d){return F[a](b,c,d)},jsCall_iiiii:function(a,b,c,d,e){return F[a](b,c,d,e)},jsCall_iiiiii:function(a,b,c,d,e,g){return F[a](b,c,d,e,g)},jsCall_iiiiiii:function(a,b,c,d,e,g,l){return F[a](b,c,d,e,g,l)},jsCall_iiiij:function(a,b,c,d,e){return F[a](b,c,d,e)},jsCall_iij:function(a,b,c){return F[a](b,c)},jsCall_iiji:function(a,b,c,d){return F[a](b,c,d)},jsCall_iijii:function(a,b,c,d,e){return F[a](b,c,d,e)},jsCall_vi:function(a,b){F[a](b)},jsCall_vii:function(a,
b,c){F[a](b,c)},jsCall_viii:function(a,b,c,d){F[a](b,c,d)},jsCall_viiii:function(a,b,c,d,e){F[a](b,c,d,e)},jsCall_viiiij:function(a,b,c,d,e,g){F[a](b,c,d,e,g)},jsCall_viij:function(a,b,c,d){F[a](b,c,d)},jsCall_viji:function(a,b,c,d){F[a](b,c,d)},___assert_fail:function(a,b,c,d){y("Assertion failed: "+H(a)+", at: "+[b?H(b):"unknown filename",c,d?H(d):"unknown function"])},___buildEnvironment:Bb,___setErrNo:Db,___syscall10:function(a,b){W=b;try{var c=Y();ta(c);return 0}catch(d){return"undefined"!==
typeof FS&&d instanceof L||y(d),-d.g}},___syscall118:function(a,b){W=b;try{return Xc(),0}catch(c){return"undefined"!==typeof FS&&c instanceof L||y(c),-c.g}},___syscall140:function(a,b){W=b;try{var c=Xc();X();var d=X(),e=X(),g=X();Qc(c,d,g);C[e>>2]=c.position;c.ea&&0===d&&0===g&&(c.ea=null);return 0}catch(l){return"undefined"!==typeof FS&&l instanceof L||y(l),-l.g}},___syscall15:function(a,b){W=b;try{var c=Y(),d=X();ha(c,d);return 0}catch(e){return"undefined"!==typeof FS&&e instanceof L||y(e),-e.g}},
___syscall183:function(a,b){W=b;try{var c=X(),d=X();if(0===d)return-K.h;if(d<ma("/")+1)return-K.Aa;na("/",G,c,d);return c}catch(e){return"undefined"!==typeof FS&&e instanceof L||y(e),-e.g}},___syscall192:function(a,b){W=b;try{var c=X(),d=X(),e=X(),g=X(),l=X(),n=X();n<<=12;a=!1;if(-1===l){var v=gd(16384,d);if(!v)return-K.ka;hd(v,0,d);a=!0}else{var A=R[l];if(!A)return-K.m;b=G;if(1===(A.flags&2097155))throw new L(K.L);if(!A.f.X)throw new L(K.S);var w=A.f.X(A,b,c,d,n,e,g);v=w.Va;a=w.aa}Vc[v]={Ta:v,Sa:d,
aa:a,fd:l,flags:g};return v}catch(O){return"undefined"!==typeof FS&&O instanceof L||y(O),-O.g}},___syscall194:function(a,b){W=b;try{var c=X();assert(0===X());var d=X(),e=X();0<=d?assert(0===e):assert(-1===e);var g=R[c];if(!g)throw new L(K.m);if(0===(g.flags&2097155))throw new L(K.h);Oc(g.node,d);return 0}catch(l){return"undefined"!==typeof FS&&l instanceof L||y(l),-l.g}},___syscall195:function(a,b){W=b;try{var c=Y(),d=X();return Wc(qa,c,d)}catch(e){return"undefined"!==typeof FS&&e instanceof L||y(e),
-e.g}},___syscall196:function(a,b){W=b;try{var c=Y(),d=X();return Wc(Mc,c,d)}catch(e){return"undefined"!==typeof FS&&e instanceof L||y(e),-e.g}},___syscall197:function(a,b){W=b;try{var c=Xc(),d=X();return Wc(qa,c.path,d)}catch(e){return"undefined"!==typeof FS&&e instanceof L||y(e),-e.g}},___syscall20:function(a,b){W=b;return 42},___syscall201:function(){return Yc.apply(null,arguments)},___syscall207:function(a,b){W=b;try{var c=X();X();X();var d=R[c];if(!d)throw new L(K.m);Nc(d.node);return 0}catch(e){return"undefined"!==
typeof FS&&e instanceof L||y(e),-e.g}},___syscall212:function(a,b){W=b;try{var c=Y();X();X();Nc(c);return 0}catch(d){return"undefined"!==typeof FS&&d instanceof L||y(d),-d.g}},___syscall221:function(a,b){W=b;try{var c=Xc();switch(X()){case 0:var d=X();return 0>d?-K.h:p(c.path,c.flags,0,d).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return d=X(),c.flags|=d,0;case 12:case 12:return d=X(),Ma[d+0>>1]=2,0;case 13:case 14:case 13:case 14:return 0;case 16:case 8:return-K.h;case 9:return Db(K.h),
-1;default:return-K.h}}catch(e){return"undefined"!==typeof FS&&e instanceof L||y(e),-e.g}},___syscall3:function(a,b){W=b;try{var c=Xc(),d=X(),e=X();return ra(c,k,d,e)}catch(g){return"undefined"!==typeof FS&&g instanceof L||y(g),-g.g}},___syscall33:function(a,b){W=b;try{var c=Y();var d=X();if(d&-8)var e=-K.h;else{var g=U(c,{G:!0}).node;a="";d&4&&(a+="r");d&2&&(a+="w");d&1&&(a+="x");e=a&&cc(g,a)?-K.L:0}return e}catch(l){return"undefined"!==typeof FS&&l instanceof L||y(l),-l.g}},___syscall39:function(a,
b){W=b;try{var c=Y(),d=X();a=c;a=Fb(a);"/"===a[a.length-1]&&(a=a.substr(0,a.length-1));V(a,d);return 0}catch(e){return"undefined"!==typeof FS&&e instanceof L||y(e),-e.g}},___syscall4:function(a,b){W=b;try{var c=Xc(),d=X(),e=X();return ia(c,k,d,e)}catch(g){return"undefined"!==typeof FS&&g instanceof L||y(g),-g.g}},___syscall40:function(a,b){W=b;try{var c=Y(),d=U(c,{parent:!0}).node,e=Hb(c),g=P(d,e),l=Fc(d,e,!0);if(l)throw new L(l);if(!d.c.rmdir)throw new L(K.B);if(g.I)throw new L(K.M);try{T.willDeletePath&&
T.willDeletePath(c)}catch(n){console.log("FS.trackingDelegate['willDeletePath']('"+c+"') threw an exception: "+n.message)}d.c.rmdir(d,e);bc(g);try{if(T.onDeletePath)T.onDeletePath(c)}catch(n){console.log("FS.trackingDelegate['onDeletePath']('"+c+"') threw an exception: "+n.message)}return 0}catch(n){return"undefined"!==typeof FS&&n instanceof L||y(n),-n.g}},___syscall5:function(a,b){W=b;try{var c=Y(),d=X(),e=X();return p(c,d,e).fd}catch(g){return"undefined"!==typeof FS&&g instanceof L||y(g),-g.g}},
___syscall6:function(a,b){W=b;try{var c=Xc();ja(c);return 0}catch(d){return"undefined"!==typeof FS&&d instanceof L||y(d),-d.g}},___syscall85:function(a,b){W=b;try{var c=Y(),d=X();var e=X();if(0>=e)var g=-K.h;else{var l=Yb(c),n=Math.min(e,ma(l)),v=k[d+n];na(l,G,d,e+1);k[d+n]=v;g=n}return g}catch(A){return"undefined"!==typeof FS&&A instanceof L||y(A),-A.g}},___syscall91:function(a,b){W=b;try{var c=X(),d=X(),e=Vc[c];if(!e)return 0;if(d===e.Sa){var g=R[e.fd],l=e.flags,n=new Uint8Array(G.subarray(c,c+
d));g&&g.f.Y&&g.f.Y(g,n,0,d,l);Vc[c]=null;e.aa&&da(e.Ta)}return 0}catch(v){return"undefined"!==typeof FS&&v instanceof L||y(v),-v.g}},___syscall94:function(a,b){W=b;try{var c=X(),d=X(),e=R[c];if(!e)throw new L(K.m);ha(e.node,d);return 0}catch(g){return"undefined"!==typeof FS&&g instanceof L||y(g),-g.g}},_emscripten_memcpy_big:function(a,b,c){G.set(G.subarray(b,b+c),a);return a},_getenv:Zc,_gettimeofday:function(a){var b=Date.now();C[a>>2]=b/1E3|0;C[a+4>>2]=b%1E3*1E3|0;return 0},_llvm_log10_f64:function(){return $c.apply(null,
arguments)},_llvm_trap:function(){y("trap!")},_localtime:function(a){ad();a=new Date(1E3*C[a>>2]);C[Z>>2]=a.getSeconds();C[Z+4>>2]=a.getMinutes();C[Z+8>>2]=a.getHours();C[Z+12>>2]=a.getDate();C[Z+16>>2]=a.getMonth();C[Z+20>>2]=a.getFullYear()-1900;C[Z+24>>2]=a.getDay();var b=new Date(a.getFullYear(),0,1);C[Z+28>>2]=(a.getTime()-b.getTime())/864E5|0;C[Z+36>>2]=-(60*a.getTimezoneOffset());var c=(new Date(2E3,6,1)).getTimezoneOffset();b=b.getTimezoneOffset();a=(c!=b&&a.getTimezoneOffset()==Math.min(b,
c))|0;C[Z+32>>2]=a;a=C[ed()+(a?4:0)>>2];C[Z+40>>2]=a;return Z},_nanosleep:function(a,b){var c=C[a>>2];a=C[a+4>>2];0!==b&&(C[b>>2]=0,C[b+4>>2]=0);return fd(1E6*c+a/1E3)},_sysconf:function(a){switch(a){case 30:return 16384;case 85:return 131068;case 132:case 133:case 12:case 137:case 138:case 15:case 235:case 16:case 17:case 18:case 19:case 20:case 149:case 13:case 10:case 236:case 153:case 9:case 21:case 22:case 159:case 154:case 14:case 77:case 78:case 139:case 80:case 81:case 82:case 68:case 67:case 164:case 11:case 29:case 47:case 48:case 95:case 52:case 51:case 46:return 200809;
case 79:return 0;case 27:case 246:case 127:case 128:case 23:case 24:case 160:case 161:case 181:case 182:case 242:case 183:case 184:case 243:case 244:case 245:case 165:case 178:case 179:case 49:case 50:case 168:case 169:case 175:case 170:case 171:case 172:case 97:case 76:case 32:case 173:case 35:return-1;case 176:case 177:case 7:case 155:case 8:case 157:case 125:case 126:case 92:case 93:case 129:case 130:case 131:case 94:case 91:return 1;case 74:case 60:case 69:case 70:case 4:return 1024;case 31:case 42:case 72:return 32;
case 87:case 26:case 33:return 2147483647;case 34:case 1:return 47839;case 38:case 36:return 99;case 43:case 37:return 2048;case 0:return 2097152;case 3:return 65536;case 28:return 32768;case 44:return 32767;case 75:return 16384;case 39:return 1E3;case 89:return 700;case 71:return 256;case 40:return 255;case 2:return 100;case 180:return 64;case 25:return 20;case 5:return 16;case 6:return 6;case 73:return 4;case 84:return"object"===typeof navigator?navigator.hardwareConcurrency||1:1}Db(K.h);return-1},
_time:function(a){var b=Date.now()/1E3|0;a&&(C[a>>2]=b);return b},_utimes:function(a,b){if(b){var c=1E3*C[b+8>>2];c+=C[b+12>>2]/1E3}else c=Date.now();a=H(a);try{b=c;var d=U(a,{G:!0}).node;d.c.l(d,{timestamp:Math.max(b,c)});return 0}catch(e){a=e;if(!(a instanceof L)){a+=" : ";a:{d=Error();if(!d.stack){try{throw Error(0);}catch(g){d=g}if(!d.stack){d="(no stack trace available)";break a}}d=d.stack.toString()}f.extraStackTrace&&(d+="\n"+f.extraStackTrace());d=Za(d);throw a+d;}Db(a.g);return-1}},DYNAMICTOP_PTR:D,
STACKTOP:hb};var id=f.asm(f.Fa,f.Ga,buffer);f.asm=id;f._RegisterExtensionFunctions=function(){return f.asm._RegisterExtensionFunctions.apply(null,arguments)};var Ab=f.___emscripten_environ_constructor=function(){return f.asm.___emscripten_environ_constructor.apply(null,arguments)};f.___errno_location=function(){return f.asm.___errno_location.apply(null,arguments)};
var dd=f.__get_daylight=function(){return f.asm.__get_daylight.apply(null,arguments)},cd=f.__get_timezone=function(){return f.asm.__get_timezone.apply(null,arguments)},ed=f.__get_tzname=function(){return f.asm.__get_tzname.apply(null,arguments)},kb=f._emscripten_replace_memory=function(){return f.asm._emscripten_replace_memory.apply(null,arguments)},da=f._free=function(){return f.asm._free.apply(null,arguments)},Xa=f._malloc=function(){return f.asm._malloc.apply(null,arguments)},gd=f._memalign=function(){return f.asm._memalign.apply(null,
arguments)},hd=f._memset=function(){return f.asm._memset.apply(null,arguments)};f._sqlite3_bind_blob=function(){return f.asm._sqlite3_bind_blob.apply(null,arguments)};f._sqlite3_bind_double=function(){return f.asm._sqlite3_bind_double.apply(null,arguments)};f._sqlite3_bind_int=function(){return f.asm._sqlite3_bind_int.apply(null,arguments)};f._sqlite3_bind_parameter_index=function(){return f.asm._sqlite3_bind_parameter_index.apply(null,arguments)};
f._sqlite3_bind_text=function(){return f.asm._sqlite3_bind_text.apply(null,arguments)};f._sqlite3_changes=function(){return f.asm._sqlite3_changes.apply(null,arguments)};f._sqlite3_clear_bindings=function(){return f.asm._sqlite3_clear_bindings.apply(null,arguments)};f._sqlite3_close_v2=function(){return f.asm._sqlite3_close_v2.apply(null,arguments)};f._sqlite3_column_blob=function(){return f.asm._sqlite3_column_blob.apply(null,arguments)};
f._sqlite3_column_bytes=function(){return f.asm._sqlite3_column_bytes.apply(null,arguments)};f._sqlite3_column_double=function(){return f.asm._sqlite3_column_double.apply(null,arguments)};f._sqlite3_column_name=function(){return f.asm._sqlite3_column_name.apply(null,arguments)};f._sqlite3_column_text=function(){return f.asm._sqlite3_column_text.apply(null,arguments)};f._sqlite3_column_type=function(){return f.asm._sqlite3_column_type.apply(null,arguments)};
f._sqlite3_create_function_v2=function(){return f.asm._sqlite3_create_function_v2.apply(null,arguments)};f._sqlite3_data_count=function(){return f.asm._sqlite3_data_count.apply(null,arguments)};f._sqlite3_errmsg=function(){return f.asm._sqlite3_errmsg.apply(null,arguments)};f._sqlite3_exec=function(){return f.asm._sqlite3_exec.apply(null,arguments)};f._sqlite3_finalize=function(){return f.asm._sqlite3_finalize.apply(null,arguments)};
f._sqlite3_free=function(){return f.asm._sqlite3_free.apply(null,arguments)};f._sqlite3_open=function(){return f.asm._sqlite3_open.apply(null,arguments)};f._sqlite3_prepare_v2=function(){return f.asm._sqlite3_prepare_v2.apply(null,arguments)};f._sqlite3_reset=function(){return f.asm._sqlite3_reset.apply(null,arguments)};f._sqlite3_result_double=function(){return f.asm._sqlite3_result_double.apply(null,arguments)};f._sqlite3_result_null=function(){return f.asm._sqlite3_result_null.apply(null,arguments)};
f._sqlite3_result_text=function(){return f.asm._sqlite3_result_text.apply(null,arguments)};f._sqlite3_step=function(){return f.asm._sqlite3_step.apply(null,arguments)};f._sqlite3_value_blob=function(){return f.asm._sqlite3_value_blob.apply(null,arguments)};f._sqlite3_value_bytes=function(){return f.asm._sqlite3_value_bytes.apply(null,arguments)};f._sqlite3_value_double=function(){return f.asm._sqlite3_value_double.apply(null,arguments)};
f._sqlite3_value_int=function(){return f.asm._sqlite3_value_int.apply(null,arguments)};f._sqlite3_value_text=function(){return f.asm._sqlite3_value_text.apply(null,arguments)};f._sqlite3_value_type=function(){return f.asm._sqlite3_value_type.apply(null,arguments)};var h=f.stackAlloc=function(){return f.asm.stackAlloc.apply(null,arguments)},pa=f.stackRestore=function(){return f.asm.stackRestore.apply(null,arguments)},la=f.stackSave=function(){return f.asm.stackSave.apply(null,arguments)};
f.dynCall_vi=function(){return f.asm.dynCall_vi.apply(null,arguments)};f.asm=id;f.cwrap=function(a,b,c,d){c=c||[];var e=c.every(function(a){return"number"===a});return"string"!==b&&e&&!d?Ja(a):function(){var d=c,e=arguments,n=Ja(a),v=[],A=0;if(e)for(var w=0;w<e.length;w++){var O=La[d[w]];O?(0===A&&(A=la()),v[w]=O(e[w])):v[w]=e[w]}d=n.apply(null,v);d="string"===b?H(d):"boolean"===b?!!d:d;0!==A&&pa(A);return d}};f.stackSave=la;f.stackRestore=pa;f.stackAlloc=h;
yb=function jd(){f.calledRun||kd();f.calledRun||(yb=jd)};
function kd(){function a(){if(!f.calledRun&&(f.calledRun=!0,!Ia)){tb||(tb=!0,nb(pb));nb(qb);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var a=f.postRun.shift();sb.unshift(a)}nb(sb)}}if(!(0<I)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)ub();nb(ob);0<I||f.calledRun||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},
1);a()},1)):a())}}f.run=kd;function y(a){if(f.onAbort)f.onAbort(a);void 0!==a?(Ba(a),z(a),a=JSON.stringify(a)):a="";Ia=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}f.abort=y;if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();f.noExitRuntime=!0;kd();
 
  return Module;
})(Module);

if (typeof exports === 'object' && typeof module === 'object')
    module.exports = Module;
else if (typeof define === 'function' && define['amd'])
    define([], function() { return Module; });
else if (typeof exports === 'object')
    exports["Module"] = Module;