
// We are modularizing this manually because the current modularize setting in Emscripten has some issues:
// https://github.com/kripken/emscripten/issues/5820
// In addition, When you use emcc's modularization, it still expects to export a global object called `Module`,
// which is able to be used/called before the WASM is loaded.
// The modularization below exports a promise that loads and resolves to the actual sql.js module.
// That way, this module can't be used before the WASM is finished loading.

// We are going to define a function that a user will call to start loading initializing our Sql.js library
// However, that function might be called multiple times, and on subsequent calls, we don't actually want it to instantiate a new instance of the Module
// Instead, we want to return the previously loaded module

// TODO: Make this not declare a global if used in the browser
var initSqlJsPromise = undefined;

var initSqlJs = function (moduleConfig) {

    if (initSqlJsPromise){
      return initSqlJsPromise;
    }
    // If we're here, we've never called this function before
    initSqlJsPromise = new Promise((resolveModule, reject) => {

        // We are modularizing this manually because the current modularize setting in Emscripten has some issues:
        // https://github.com/kripken/emscripten/issues/5820

        // The way to affect the loading of emcc compiled modules is to create a variable called `Module` and add
        // properties to it, like `preRun`, `postRun`, etc
        // We are using that to get notified when the WASM has finished loading.
        // Only then will we return our promise

        // If they passed in a moduleConfig object, use that
        // Otherwise, initialize Module to the empty object
        var Module = typeof moduleConfig !== 'undefined' ? moduleConfig : {};

        // EMCC only allows for a single onAbort function (not an array of functions)
        // So if the user defined their own onAbort function, we remember it and call it
        var originalOnAbortFunction = Module['onAbort'];
        Module['onAbort'] = function (errorThatCausedAbort) {
            reject(new Error(errorThatCausedAbort));
            if (originalOnAbortFunction){
              originalOnAbortFunction(errorThatCausedAbort);
            }
        };

        Module['postRun'] = Module['postRun'] || [];
        Module['postRun'].push(function () {
            // When Emscripted calls postRun, this promise resolves with the built Module
            resolveModule(Module);
        });

        // There is a section of code in the emcc-generated code below that looks like this:
        // (Note that this is lowercase `module`)
        // if (typeof module !== 'undefined') {
        //     module['exports'] = Module;
        // }
        // When that runs, it's going to overwrite our own modularization export efforts in shell-post.js!
        // The only way to tell emcc not to emit it is to pass the MODULARIZE=1 or MODULARIZE_INSTANCE=1 flags,
        // but that carries with it additional unnecessary baggage/bugs we don't want either.
        // So, we have three options:
        // 1) We undefine `module`
        // 2) We remember what `module['exports']` was at the beginning of this function and we restore it later
        // 3) We write a script to remove those lines of code as part of the Make process.
        //
        // Since those are the only lines of code that care about module, we will undefine it. It's the most straightforward
        // of the options, and has the side effect of reducing emcc's efforts to modify the module if its output were to change in the future.
        // That's a nice side effect since we're handling the modularization efforts ourselves
        module = undefined;
        
        // The emcc-generated code and shell-post.js code goes below,
        // meaning that all of it runs inside of this promise. If anything throws an exception, our promise will abort
function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ba(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}var ca="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this,ha="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
function ia(a,b){if(b){var c=ca;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ha(c,a,{configurable:!0,writable:!0,value:b})}}
ia("Promise",function(a){function b(a){this.lb=0;this.tb=void 0;this.fb=[];var b=this.nb();try{a(b.resolve,b.reject)}catch(x){b.reject(x)}}function c(){this.fb=null}function d(a){return a instanceof b?a:new b(function(b){b(a)})}if(a)return a;c.prototype.lb=function(a){if(null==this.fb){this.fb=[];var b=this;this.nb(function(){b.tb()})}this.fb.push(a)};var e=ca.setTimeout;c.prototype.nb=function(a){e(a,0)};c.prototype.tb=function(){for(;this.fb&&this.fb.length;){var a=this.fb;this.fb=[];for(var b=
0;b<a.length;++b){var c=a[b];a[b]=null;try{c()}catch(y){this.sb(y)}}}this.fb=null};c.prototype.sb=function(a){this.nb(function(){throw a;})};b.prototype.nb=function(){function a(a){return function(d){c||(c=!0,a.call(b,d))}}var b=this,c=!1;return{resolve:a(this.Pb),reject:a(this.sb)}};b.prototype.Pb=function(a){if(a===this)this.sb(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof b)this.Rb(a);else{a:switch(typeof a){case "object":var c=null!=a;break a;case "function":c=!0;break a;
default:c=!1}c?this.Ob(a):this.Fb(a)}};b.prototype.Ob=function(a){var b=void 0;try{b=a.then}catch(x){this.sb(x);return}"function"==typeof b?this.Tb(b,a):this.Fb(a)};b.prototype.sb=function(a){this.Gb(2,a)};b.prototype.Fb=function(a){this.Gb(1,a)};b.prototype.Gb=function(a,b){if(0!=this.lb)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.lb);this.lb=a;this.tb=b;this.Nb()};b.prototype.Nb=function(){if(null!=this.fb){for(var a=0;a<this.fb.length;++a)g.lb(this.fb[a]);this.fb=
null}};var g=new c;b.prototype.Rb=function(a){var b=this.nb();a.Db(b.resolve,b.reject)};b.prototype.Tb=function(a,b){var c=this.nb();try{a.call(b,c.resolve,c.reject)}catch(y){c.reject(y)}};b.prototype.then=function(a,c){function d(a,b){return"function"==typeof a?function(b){try{e(a(b))}catch(Oa){g(Oa)}}:b}var e,g,k=new b(function(a,b){e=a;g=b});this.Db(d(a,e),d(c,g));return k};b.prototype.catch=function(a){return this.then(void 0,a)};b.prototype.Db=function(a,b){function c(){switch(d.lb){case 1:a(d.tb);
break;case 2:b(d.tb);break;default:throw Error("Unexpected state: "+d.lb);}}var d=this;null==this.fb?g.lb(c):this.fb.push(c)};b.resolve=d;b.reject=function(a){return new b(function(b,c){c(a)})};b.race=function(a){return new b(function(b,c){for(var e=ba(a),g=e.next();!g.done;g=e.next())d(g.value).Db(b,c)})};b.all=function(a){var c=ba(a),e=c.next();return e.done?d([]):new b(function(a,b){function g(b){return function(c){k[b]=c;m--;0==m&&a(k)}}var k=[],m=0;do k.push(void 0),m++,d(e.value).Db(g(k.length-
1),b),e=c.next();while(!e.done)})};return b});var f,h;var l;l||(l=typeof Module !== 'undefined' ? Module : {});
var Aa=function(){function a(a){this.filename="dbfile_"+(4294967295*Math.random()>>>0);if(null!=a){var b=this.filename,c=b?n("/",b):"/";b=ja(!0,!0);c=ka(c,(void 0!==b?b:438)&4095|32768,0);if(a){if("string"===typeof a){for(var e=Array(a.length),ra=0,k=a.length;ra<k;++ra)e[ra]=a.charCodeAt(ra);a=e}la(c,b|146);e=p(c,"w");ma(e,a,0,a.length,0,void 0);na(e);la(c,b)}}this.handleError(g(this.filename,d));this.fb=q(d,"i32");ec(this.fb);this.Jb={}}function b(a,b){this.fb=a;this.nb=b;this.lb=1;this.sb=[]}var c;
var d=r(4);var e={};b.prototype.bind=function(a){if(!this.fb)throw"Statement closed";this.reset();return Array.isArray(a)?this.Nb(a):this.Ob(a)};b.prototype.step=function(){var a;if(!this.fb)throw"Statement closed";this.lb=1;switch(a=fc(this.fb)){case e.fc:return!0;case e.DONE:return!1;default:return this.nb.handleError(a)}};b.prototype.pc=function(a){a=void 0===a?this.lb++:a;return hc(this.fb,a)};b.prototype.rc=function(a){a=void 0===a?this.lb++:a;return ic(this.fb,a)};b.prototype.Fb=function(a){a=
void 0===a?this.lb++:a;var b;var c=jc(this.fb,a);var d=kc(this.fb,a);var e=new Uint8Array(c);for(a=b=0;0<=c?b<c:b>c;a=0<=c?++b:--b)e[a]=t[d+a];return e};b.prototype.get=function(a){var b,c;null!=a&&this.bind(a)&&this.step();var d=[];a=b=0;for(c=sb(this.fb);0<=c?b<c:b>c;a=0<=c?++b:--b)switch(lc(this.fb,a)){case e.ec:case e.FLOAT:d.push(this.pc(a));break;case e.hc:d.push(this.rc(a));break;case e.dc:d.push(this.Fb(a));break;default:d.push(null)}return d};b.prototype.getColumnNames=function(){var a,b;
var c=[];var d=a=0;for(b=sb(this.fb);0<=b?a<b:a>b;d=0<=b?++a:--a)c.push(mc(this.fb,d));return c};b.prototype.getAsObject=function(a){var b,c;var d=this.get(a);var e=this.getColumnNames();var g={};a=b=0;for(c=e.length;b<c;a=++b){var k=e[a];g[k]=d[a]}return g};b.prototype.run=function(a){null!=a&&this.bind(a);this.step();return this.reset()};b.prototype.Tb=function(a,b){b=void 0===b?this.lb++:b;var c;a=oa(a);this.sb.push(c=pa(a));this.nb.handleError(ea(this.fb,b,c,a.length-1,0))};b.prototype.Gb=function(a,
b){b=void 0===b?this.lb++:b;var c;this.sb.push(c=pa(a));this.nb.handleError(Na(this.fb,b,c,a.length,0))};b.prototype.Rb=function(a,b){b=void 0===b?this.lb++:b;this.nb.handleError((a===(a|0)?dc:cc)(this.fb,b,a))};b.prototype.Pb=function(a){a=void 0===a?this.lb++:a;Na(this.fb,a,0,0,0)};b.prototype.tb=function(a,b){b=void 0===b?this.lb++:b;switch(typeof a){case "string":this.Tb(a,b);break;case "number":case "boolean":this.Rb(a+0,b);break;case "object":if(null===a)this.Pb(b);else if(null!=a.length)this.Gb(a,
b);else throw"Wrong API use : tried to bind a value of an unknown type ("+a+").";}};b.prototype.Ob=function(a){var b;for(b in a){var c=a[b];var d=Oa(this.fb,b);0!==d&&this.tb(c,d)}return!0};b.prototype.Nb=function(a){var b,c;var d=b=0;for(c=a.length;b<c;d=++b){var e=a[d];this.tb(e,d+1)}return!0};b.prototype.reset=function(){this.freemem();return nc(this.fb)===e.Cb&&oc(this.fb)===e.Cb};b.prototype.freemem=function(){for(var a;a=this.sb.pop();)qa(a);return null};b.prototype.free=function(){this.freemem();
var a=pc(this.fb)===e.Cb;delete this.nb.Jb[this.fb];this.fb=fa;return a};a.prototype.run=function(a,b){if(!this.fb)throw"Database closed";b?(a=this.prepare(a,b),a.step(),a.free()):this.handleError(m(this.fb,a,0,0,d));return this};a.prototype.exec=function(a){if(!this.fb)throw"Database closed";var c=sa();var e=ta(a)+1;var g=r(e);u(a,t,g,e);a=g;e=r(4);for(g=[];q(a,"i8")!==fa;){ua(d);ua(e);this.handleError(da(this.fb,a,-1,d,e));var k=q(d,"i32");a=q(e,"i32");if(k!==fa){var m=new b(k,this);for(k=null;m.step();)null===
k&&(k={columns:m.getColumnNames(),values:[]},g.push(k)),k.values.push(m.get());m.free()}}va(c);return g};a.prototype.each=function(a,b,c,d){"function"===typeof b&&(d=c,c=b,b=void 0);for(a=this.prepare(a,b);a.step();)c(a.getAsObject());a.free();if("function"===typeof d)return d()};a.prototype.prepare=function(a,c){ua(d);this.handleError(y(this.fb,a,-1,d,fa));a=q(d,"i32");if(a===fa)throw"Nothing to prepare";var e=new b(a,this);null!=c&&e.bind(c);return this.Jb[a]=e};a.prototype["export"]=function(){var a;
var b=this.Jb;for(e in b){var c=b[e];c.free()}this.handleError(k(this.fb));c=this.filename;var e=e={encoding:"binary"};e.flags=e.flags||"r";e.encoding=e.encoding||"binary";if("utf8"!==e.encoding&&"binary"!==e.encoding)throw Error('Invalid encoding type "'+e.encoding+'"');b=p(c,e.flags);c=wa(c).size;var m=new Uint8Array(c);xa(b,m,0,c,0);"utf8"===e.encoding?a=v(m,0):"binary"===e.encoding&&(a=m);na(b);this.handleError(g(this.filename,d));this.fb=q(d,"i32");return a};a.prototype.close=function(){var a;
var b=this.Jb;for(a in b){var c=b[a];c.free()}this.handleError(k(this.fb));ya("/"+this.filename);return this.fb=null};a.prototype.handleError=function(a){if(a===e.Cb)return null;a=qc(this.fb);throw Error(a);};a.prototype.getRowsModified=function(){return x(this.fb)};a.prototype.create_function=function(a,b){var c=za(function(a,c,d){var e,g;var k=[];for(e=g=0;0<=c?g<c:g>c;e=0<=c?++g:--g){var m=q(d+4*e,"i32");var y=sc(m);e=function(){switch(!1){case 1!==y:return tc;case 2!==y:return uc;case 3!==y:return vc;
case 4!==y:return function(a){var b,c;var d=wc(a);var e=xc(a);a=new Uint8Array(d);for(b=c=0;0<=d?c<d:c>d;b=0<=d?++c:--c)a[b]=t[e+b];return a};default:return function(){return null}}}();e=e(m);k.push(e)}if(c=b.apply(null,k))switch(typeof c){case "number":return yc(a,c);case "string":return zc(a,c,-1,-1)}else return Ac(a)});this.handleError(Bc(this.fb,a,b.length,e.ic,0,c,0,0,0));return this};var g=l.cwrap("sqlite3_open","number",["string","number"]);var k=l.cwrap("sqlite3_close_v2","number",["number"]);
var m=l.cwrap("sqlite3_exec","number",["number","string","number","number","number"]);l.cwrap("sqlite3_free","",["number"]);var x=l.cwrap("sqlite3_changes","number",["number"]);var y=l.cwrap("sqlite3_prepare_v2","number",["number","string","number","number","number"]);var da=l.cwrap("sqlite3_prepare_v2","number",["number","number","number","number","number"]);var ea=l.cwrap("sqlite3_bind_text","number",["number","number","number","number","number"]);var Na=l.cwrap("sqlite3_bind_blob","number",["number",
"number","number","number","number"]);var cc=l.cwrap("sqlite3_bind_double","number",["number","number","number"]);var dc=l.cwrap("sqlite3_bind_int","number",["number","number","number"]);var Oa=l.cwrap("sqlite3_bind_parameter_index","number",["number","string"]);var fc=l.cwrap("sqlite3_step","number",["number"]);var qc=l.cwrap("sqlite3_errmsg","string",["number"]);var sb=l.cwrap("sqlite3_data_count","number",["number"]);var hc=l.cwrap("sqlite3_column_double","number",["number","number"]);var ic=l.cwrap("sqlite3_column_text",
"string",["number","number"]);var kc=l.cwrap("sqlite3_column_blob","number",["number","number"]);var jc=l.cwrap("sqlite3_column_bytes","number",["number","number"]);var lc=l.cwrap("sqlite3_column_type","number",["number","number"]);var mc=l.cwrap("sqlite3_column_name","string",["number","number"]);var oc=l.cwrap("sqlite3_reset","number",["number"]);var nc=l.cwrap("sqlite3_clear_bindings","number",["number"]);var pc=l.cwrap("sqlite3_finalize","number",["number"]);var Bc=l.cwrap("sqlite3_create_function_v2",
"number","number string number number number number number number number".split(" "));var sc=l.cwrap("sqlite3_value_type","number",["number"]);var wc=l.cwrap("sqlite3_value_bytes","number",["number"]);var vc=l.cwrap("sqlite3_value_text","string",["number"]);var tc=l.cwrap("sqlite3_value_int","number",["number"]);var xc=l.cwrap("sqlite3_value_blob","number",["number"]);var uc=l.cwrap("sqlite3_value_double","number",["number"]);var yc=l.cwrap("sqlite3_result_double","",["number","number"]);var Ac=l.cwrap("sqlite3_result_null",
"",["number"]);var zc=l.cwrap("sqlite3_result_text","",["number","string","number","number"]);var ec=l.cwrap("RegisterExtensionFunctions","number",["number"]);this.SQL={Database:a};for(c in this.SQL)l[c]=this.SQL[c];var fa=0;e.Cb=0;e.Bc=1;e.Ec=2;e.Oc=3;e.vc=4;e.xc=5;e.Hc=6;e.NOMEM=7;e.Rc=8;e.Fc=9;e.Gc=10;e.Ac=11;e.NOTFOUND=12;e.Dc=13;e.yc=14;e.Pc=15;e.EMPTY=16;e.Sc=17;e.Tc=18;e.zc=19;e.Ic=20;e.Jc=21;e.Kc=22;e.wc=23;e.Cc=24;e.Qc=25;e.Lc=26;e.Mc=27;e.Uc=28;e.fc=100;e.DONE=101;e.ec=1;e.FLOAT=2;e.hc=
3;e.dc=4;e.Nc=5;e.ic=1}.bind(this);l.preRun=l.preRun||[];l.preRun.push(Aa);var Ba={},w;for(w in l)l.hasOwnProperty(w)&&(Ba[w]=l[w]);l.arguments=[];l.thisProgram="./this.program";l.quit=function(a,b){throw b;};l.preRun=[];l.postRun=[];var Ca=!1,z=!1,A=!1,Da=!1;Ca="object"===typeof window;z="function"===typeof importScripts;A="object"===typeof process&&"function"===typeof require&&!Ca&&!z;Da=!Ca&&!A&&!z;var B="";
if(A){B=__dirname+"/";var Ea,Fa;l.read=function(a,b){Ea||(Ea=require("fs"));Fa||(Fa=require("path"));a=Fa.normalize(a);a=Ea.readFileSync(a);return b?a:a.toString()};l.readBinary=function(a){a=l.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(l.thisProgram=process.argv[1].replace(/\\/g,"/"));l.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=l);process.on("unhandledRejection",C);l.quit=function(a){process.exit(a)};l.inspect=
function(){return"[Emscripten Module object]"}}else if(Da)"undefined"!=typeof read&&(l.read=function(a){return read(a)}),l.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?l.arguments=scriptArgs:"undefined"!=typeof arguments&&(l.arguments=arguments),"function"===typeof quit&&(l.quit=function(a){quit(a)});else if(Ca||z)z?B=self.location.href:document.currentScript&&(B=
document.currentScript.src),B=0!==B.indexOf("blob:")?B.substr(0,B.lastIndexOf("/")+1):"",l.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},z&&(l.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),l.readAsync=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):
c()};d.onerror=c;d.send(null)},l.setWindowTitle=function(a){document.title=a};var Ga=l.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),D=l.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||Ga);for(w in Ba)Ba.hasOwnProperty(w)&&(l[w]=Ba[w]);Ba=void 0;function Ha(a){var b=E[Ia>>2];a=b+a+15&-16;if(a<=Ja())E[Ia>>2]=a;else if(!Ka(a))return 0;return b}
var La={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}},Ma=1,F=Array(64);function za(a){for(var b=0;64>b;b++)if(!F[b])return F[b]=a,Ma+b;throw"Finished up all reserved function pointers. Use a higher value for RESERVED_FUNCTION_POINTERS.";}"object"!==typeof WebAssembly&&D("no native wasm support detected");
function q(a,b){b=b||"i8";"*"===b.charAt(b.length-1)&&(b="i32");switch(b){case "i1":return t[a>>0];case "i8":return t[a>>0];case "i16":return Pa[a>>1];case "i32":return E[a>>2];case "i64":return E[a>>2];case "float":return Qa[a>>2];case "double":return Ra[a>>3];default:C("invalid type for getValue: "+b)}return null}var Sa,Ta=!1;function assert(a,b){a||C("Assertion failed: "+b)}function Ua(a){var b=l["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
function Va(a,b,c,d){var e={string:function(a){var b=0;if(null!==a&&void 0!==a&&0!==a){var c=(a.length<<2)+1;b=r(c);u(a,G,b,c)}return b},array:function(a){var b=r(a.length);t.set(a,b);return b}},g=Ua(a),k=[];a=0;if(d)for(var m=0;m<d.length;m++){var x=e[c[m]];x?(0===a&&(a=sa()),k[m]=x(d[m])):k[m]=d[m]}c=g.apply(null,k);c=function(a){return"string"===b?H(a):"boolean"===b?!!a:a}(c);0!==a&&va(a);return c}
function ua(a){var b="i32";"*"===b.charAt(b.length-1)&&(b="i32");switch(b){case "i1":t[a>>0]=0;break;case "i8":t[a>>0]=0;break;case "i16":Pa[a>>1]=0;break;case "i32":E[a>>2]=0;break;case "i64":f=[0,(h=0,1<=+Wa(h)?0<h?(Xa(+Ya(h/4294967296),4294967295)|0)>>>0:~~+Za((h-+(~~h>>>0))/4294967296)>>>0:0)];E[a>>2]=f[0];E[a+4>>2]=f[1];break;case "float":Qa[a>>2]=0;break;case "double":Ra[a>>3]=0;break;default:C("invalid type for setValue: "+b)}}var $a=0,ab=3;
function pa(a){var b=$a;if("number"===typeof a){var c=!0;var d=a}else c=!1,d=a.length;b=b==ab?e:[bb,r,Ha][b](Math.max(d,1));if(c){var e=b;assert(0==(b&3));for(a=b+(d&-4);e<a;e+=4)E[e>>2]=0;for(a=b+d;e<a;)t[e++>>0]=0;return b}a.subarray||a.slice?G.set(a,b):G.set(new Uint8Array(a),b);return b}var cb="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function v(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&cb)return cb.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|k:(e&7)<<18|g<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function H(a){return a?v(G,a,void 0):""}
function u(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var m=a.charCodeAt(++g);k=65536+((k&1023)<<10)|m&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e}
function ta(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function db(a){return a.replace(/__Z[\w\d_]+/g,function(a){return a===a?a:a+" ["+a+"]"})}function eb(a){0<a%65536&&(a+=65536-a%65536);return a}var buffer,t,G,Pa,E,Qa,Ra;
function fb(){l.HEAP8=t=new Int8Array(buffer);l.HEAP16=Pa=new Int16Array(buffer);l.HEAP32=E=new Int32Array(buffer);l.HEAPU8=G=new Uint8Array(buffer);l.HEAPU16=new Uint16Array(buffer);l.HEAPU32=new Uint32Array(buffer);l.HEAPF32=Qa=new Float32Array(buffer);l.HEAPF64=Ra=new Float64Array(buffer)}var Ia=60800,gb=l.TOTAL_MEMORY||16777216;5242880>gb&&D("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+gb+"! (TOTAL_STACK=5242880)");
l.buffer?buffer=l.buffer:"object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(Sa=new WebAssembly.Memory({initial:gb/65536}),buffer=Sa.buffer):buffer=new ArrayBuffer(gb);fb();E[Ia>>2]=5303712;function hb(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.kc;"number"===typeof c?void 0===b.Lb?l.dynCall_v(c):l.dynCall_vi(c,b.Lb):c(void 0===b.Lb?null:b.Lb)}}}var ib=[],jb=[],kb=[],lb=[],mb=!1;function nb(){var a=l.preRun.shift();ib.unshift(a)}
var Wa=Math.abs,Za=Math.ceil,Ya=Math.floor,Xa=Math.min,I=0,ob=null,pb=null;l.preloadedImages={};l.preloadedAudios={};function qb(){var a=J;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var J="sql-wasm.wasm";if(!qb()){var rb=J;J=l.locateFile?l.locateFile(rb,B):B+rb}
function tb(){try{if(l.wasmBinary)return new Uint8Array(l.wasmBinary);if(l.readBinary)return l.readBinary(J);throw"both async and sync fetching of the wasm failed";}catch(a){C(a)}}function ub(){return l.wasmBinary||!Ca&&!z||"function"!==typeof fetch?new Promise(function(a){a(tb())}):fetch(J,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+J+"'";return a.arrayBuffer()}).catch(function(){return tb()})}
function vb(a){function b(a){l.asm=a.exports;I--;l.monitorRunDependencies&&l.monitorRunDependencies(I);0==I&&(null!==ob&&(clearInterval(ob),ob=null),pb&&(a=pb,pb=null,a()))}function c(a){b(a.instance)}function d(a){ub().then(function(a){return WebAssembly.instantiate(a,e)}).then(a,function(a){D("failed to asynchronously prepare wasm: "+a);C(a)})}var e={env:a,global:{NaN:NaN,Infinity:Infinity},"global.Math":Math,asm2wasm:La};I++;l.monitorRunDependencies&&l.monitorRunDependencies(I);if(l.instantiateWasm)try{return l.instantiateWasm(e,
b)}catch(g){return D("Module.instantiateWasm callback failed with error: "+g),!1}l.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||qb()||"function"!==typeof fetch?d(c):WebAssembly.instantiateStreaming(fetch(J,{credentials:"same-origin"}),e).then(c,function(a){D("wasm streaming compile failed: "+a);D("falling back to ArrayBuffer instantiation");d(c)});return{}}
l.asm=function(a,b){b.memory=Sa;b.table=new WebAssembly.Table({initial:2816,maximum:2816,element:"anyfunc"});b.__memory_base=1024;b.__table_base=0;return vb(b)};jb.push({kc:function(){wb()}});var K={};
function xb(a){if(xb.fb){var b=E[a>>2];var c=E[b>>2]}else xb.fb=!0,K.USER=K.LOGNAME="web_user",K.PATH="/",K.PWD="/",K.HOME="/home/web_user",K.LANG="C.UTF-8",K._=l.thisProgram,c=mb?bb(1024):Ha(1024),b=mb?bb(256):Ha(256),E[b>>2]=c,E[a>>2]=b;a=[];var d=0,e;for(e in K)if("string"===typeof K[e]){var g=e+"="+K[e];a.push(g);d+=g.length}if(1024<d)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");for(e=0;e<a.length;e++){d=g=a[e];for(var k=c,m=0;m<d.length;++m)t[k++>>0]=d.charCodeAt(m);t[k>>0]=0;E[b+
4*e>>2]=c;c+=g.length+1}E[b+4*a.length>>2]=0}function yb(a){l.___errno_location&&(E[l.___errno_location()>>2]=a);return a}function zb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function Ab(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=zb(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function Bb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Cb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function Db(){var a=Array.prototype.slice.call(arguments,0);return Ab(a.join("/"))}function n(a,b){return Ab(a+"/"+b)}
function Eb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=zb(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var Fb=[];function Gb(a,b){Fb[a]={input:[],output:[],zb:b};Hb(a,Ib)}
var Ib={open:function(a){var b=Fb[a.node.rdev];if(!b)throw new L(19);a.tty=b;a.seekable=!1},close:function(a){a.tty.zb.flush(a.tty)},flush:function(a){a.tty.zb.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.zb.bc)throw new L(6);for(var e=0,g=0;g<d;g++){try{var k=a.tty.zb.bc(a.tty)}catch(m){throw new L(5);}if(void 0===k&&0===e)throw new L(11);if(null===k||void 0===k)break;e++;b[c+g]=k}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.zb.Sb)throw new L(6);
try{for(var e=0;e<d;e++)a.tty.zb.Sb(a.tty,b[c+e])}catch(g){throw new L(5);}d&&(a.node.timestamp=Date.now());return e}},Jb={bc:function(a){if(!a.input.length){var b=null;if(A){var c=new Buffer(256),d=0,e=process.stdin.fd;if("win32"!=process.platform){var g=!1;try{e=fs.openSync("/dev/stdin","r"),g=!0}catch(k){}}try{d=fs.readSync(e,c,0,256,null)}catch(k){if(-1!=k.toString().indexOf("EOF"))d=0;else throw k;}g&&fs.closeSync(e);0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&
"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=oa(b,!0)}return a.input.shift()},Sb:function(a,b){null===b||10===b?(Ga(v(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(Ga(v(a.output,0)),a.output=[])}},Kb={Sb:function(a,b){null===b||10===b?(D(v(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&
(D(v(a.output,0)),a.output=[])}},M={rb:null,ob:function(){return M.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new L(1);M.rb||(M.rb={dir:{node:{qb:M.gb.qb,mb:M.gb.mb,lookup:M.gb.lookup,Ab:M.gb.Ab,rename:M.gb.rename,unlink:M.gb.unlink,rmdir:M.gb.rmdir,readdir:M.gb.readdir,symlink:M.gb.symlink},stream:{ub:M.jb.ub}},file:{node:{qb:M.gb.qb,mb:M.gb.mb},stream:{ub:M.jb.ub,read:M.jb.read,write:M.jb.write,Vb:M.jb.Vb,Hb:M.jb.Hb,Ib:M.jb.Ib}},link:{node:{qb:M.gb.qb,
mb:M.gb.mb,readlink:M.gb.readlink},stream:{}},Xb:{node:{qb:M.gb.qb,mb:M.gb.mb},stream:Lb}});c=Mb(a,b,c,d);N(c.mode)?(c.gb=M.rb.dir.node,c.jb=M.rb.dir.stream,c.hb={}):32768===(c.mode&61440)?(c.gb=M.rb.file.node,c.jb=M.rb.file.stream,c.kb=0,c.hb=null):40960===(c.mode&61440)?(c.gb=M.rb.link.node,c.jb=M.rb.link.stream):8192===(c.mode&61440)&&(c.gb=M.rb.Xb.node,c.jb=M.rb.Xb.stream);c.timestamp=Date.now();a&&(a.hb[b]=c);return c},Vc:function(a){if(a.hb&&a.hb.subarray){for(var b=[],c=0;c<a.kb;++c)b.push(a.hb[c]);
return b}return a.hb},Wc:function(a){return a.hb?a.hb.subarray?a.hb.subarray(0,a.kb):new Uint8Array(a.hb):new Uint8Array},Yb:function(a,b){var c=a.hb?a.hb.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.hb,a.hb=new Uint8Array(b),0<a.kb&&a.hb.set(c.subarray(0,a.kb),0))},qc:function(a,b){if(a.kb!=b)if(0==b)a.hb=null,a.kb=0;else{if(!a.hb||a.hb.subarray){var c=a.hb;a.hb=new Uint8Array(new ArrayBuffer(b));c&&a.hb.set(c.subarray(0,Math.min(b,a.kb)))}else if(a.hb||(a.hb=
[]),a.hb.length>b)a.hb.length=b;else for(;a.hb.length<b;)a.hb.push(0);a.kb=b}},gb:{qb:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;N(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.kb:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.vb=4096;b.blocks=Math.ceil(b.size/b.vb);return b},mb:function(a,b){void 0!==b.mode&&(a.mode=
b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&M.qc(a,b.size)},lookup:function(){throw Nb[2];},Ab:function(a,b,c,d){return M.createNode(a,b,c,d)},rename:function(a,b,c){if(N(a.mode)){try{var d=O(b,c)}catch(g){}if(d)for(var e in d.hb)throw new L(39);}delete a.parent.hb[a.name];a.name=c;b.hb[c]=a;a.parent=b},unlink:function(a,b){delete a.hb[b]},rmdir:function(a,b){var c=O(a,b),d;for(d in c.hb)throw new L(39);delete a.hb[b]},readdir:function(a){var b=[".",".."],c;for(c in a.hb)a.hb.hasOwnProperty(c)&&
b.push(c);return b},symlink:function(a,b,c){a=M.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new L(22);return a.link}},jb:{read:function(a,b,c,d,e){var g=a.node.hb;if(e>=a.node.kb)return 0;a=Math.min(a.node.kb-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){g=!1;if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.hb||a.hb.subarray)){if(g)return a.hb=b.subarray(c,
c+d),a.kb=d;if(0===a.kb&&0===e)return a.hb=new Uint8Array(b.subarray(c,c+d)),a.kb=d;if(e+d<=a.kb)return a.hb.set(b.subarray(c,c+d),e),d}M.Yb(a,e+d);if(a.hb.subarray&&b.subarray)a.hb.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.hb[e+g]=b[c+g];a.kb=Math.max(a.kb,e+d);return d},ub:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.kb);if(0>b)throw new L(22);return b},Vb:function(a,b,c){M.Yb(a.node,b+c);a.node.kb=Math.max(a.node.kb,b+c)},Hb:function(a,b,c,d,e,g,k){if(32768!==
(a.node.mode&61440))throw new L(19);c=a.node.hb;if(k&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<e||e+d<a.node.kb)c.subarray?c=c.subarray(e,e+d):c=Array.prototype.slice.call(c,e,e+d);a=!0;d=bb(d);if(!d)throw new L(12);b.set(c,d)}else a=!1,d=c.byteOffset;return{oc:d,Kb:a}},Ib:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new L(19);if(e&2)return 0;M.jb.write(a,b,0,d,c,!1);return 0}}},P={Eb:!1,tc:function(){P.Eb=!!process.platform.match(/^win/);var a=process.binding("constants");a.fs&&(a=a.fs);
P.Zb={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},Wb:function(a){return Buffer.fb?Buffer.from(a):new Buffer(a)},ob:function(a){assert(A);return P.createNode(null,"/",P.ac(a.Qb.root),0)},createNode:function(a,b,c){if(!N(c)&&32768!==(c&61440)&&40960!==(c&61440))throw new L(22);a=Mb(a,b,c);a.gb=P.gb;a.jb=P.jb;return a},ac:function(a){try{var b=fs.lstatSync(a);P.Eb&&(b.mode=b.mode|(b.mode&292)>>2)}catch(c){if(!c.code)throw c;throw new L(-c.ib);
}return b.mode},pb:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.ob.Qb.root);b.reverse();return Db.apply(null,b)},jc:function(a){a&=-2656257;var b=0,c;for(c in P.Zb)a&c&&(b|=P.Zb[c],a^=c);if(a)throw new L(22);return b},gb:{qb:function(a){a=P.pb(a);try{var b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new L(-c.ib);}P.Eb&&!b.vb&&(b.vb=4096);P.Eb&&!b.blocks&&(b.blocks=(b.size+b.vb-1)/b.vb|0);return{dev:b.dev,ino:b.ino,mode:b.mode,nlink:b.nlink,uid:b.uid,gid:b.gid,rdev:b.rdev,
size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,vb:b.vb,blocks:b.blocks}},mb:function(a,b){var c=P.pb(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&fs.truncateSync(c,b.size)}catch(d){if(!d.code)throw d;throw new L(-d.ib);}},lookup:function(a,b){var c=n(P.pb(a),b);c=P.ac(c);return P.createNode(a,b,c)},Ab:function(a,b,c,d){a=P.createNode(a,b,c,d);b=P.pb(a);try{N(a.mode)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,"",{mode:a.mode})}catch(e){if(!e.code)throw e;throw new L(-e.ib);
}return a},rename:function(a,b,c){a=P.pb(a);b=n(P.pb(b),c);try{fs.renameSync(a,b)}catch(d){if(!d.code)throw d;throw new L(-d.ib);}},unlink:function(a,b){a=n(P.pb(a),b);try{fs.unlinkSync(a)}catch(c){if(!c.code)throw c;throw new L(-c.ib);}},rmdir:function(a,b){a=n(P.pb(a),b);try{fs.rmdirSync(a)}catch(c){if(!c.code)throw c;throw new L(-c.ib);}},readdir:function(a){a=P.pb(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;throw new L(-b.ib);}},symlink:function(a,b,c){a=n(P.pb(a),b);try{fs.symlinkSync(c,
a)}catch(d){if(!d.code)throw d;throw new L(-d.ib);}},readlink:function(a){var b=P.pb(a);try{return b=fs.readlinkSync(b),b=Ob.relative(Ob.resolve(a.ob.Qb.root),b)}catch(c){if(!c.code)throw c;throw new L(-c.ib);}}},jb:{open:function(a){var b=P.pb(a.node);try{32768===(a.node.mode&61440)&&(a.Bb=fs.openSync(b,P.jc(a.flags)))}catch(c){if(!c.code)throw c;throw new L(-c.ib);}},close:function(a){try{32768===(a.node.mode&61440)&&a.Bb&&fs.closeSync(a.Bb)}catch(b){if(!b.code)throw b;throw new L(-b.ib);}},read:function(a,
b,c,d,e){if(0===d)return 0;try{return fs.readSync(a.Bb,P.Wb(b.buffer),c,d,e)}catch(g){throw new L(-g.ib);}},write:function(a,b,c,d,e){try{return fs.writeSync(a.Bb,P.Wb(b.buffer),c,d,e)}catch(g){throw new L(-g.ib);}},ub:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.node.mode&61440))try{b+=fs.fstatSync(a.Bb).size}catch(d){throw new L(-d.ib);}if(0>b)throw new L(22);return b}}},Pb=null,Qb={},Q=[],Rb=1,R=null,Sb=!0,S={},L=null,Nb={};
function T(a,b){a=Eb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={$b:!0,Ub:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Ub)throw new L(40);a=zb(a.split("/").filter(function(a){return!!a}),!1);var e=Pb;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;e=O(e,a[d]);c=n(c,a[d]);e.xb&&(!g||g&&b.$b)&&(e=e.xb.root);if(!g||b.wb)for(g=0;40960===(e.mode&61440);)if(e=Tb(c),c=Eb(Bb(c),e),e=T(c,{Ub:b.Ub}).node,40<g++)throw new L(40);}return{path:c,node:e}}
function Ub(a){for(var b;;){if(a===a.parent)return a=a.ob.cc,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Vb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%R.length}function Wb(a){var b=Vb(a.parent.id,a.name);a.yb=R[b];R[b]=a}function Xb(a){var b=Vb(a.parent.id,a.name);if(R[b]===a)R[b]=a.yb;else for(b=R[b];b;){if(b.yb===a){b.yb=a.yb;break}b=b.yb}}
function O(a,b){var c;if(c=(c=Yb(a,"x"))?c:a.gb.lookup?0:13)throw new L(c,a);for(c=R[Vb(a.id,b)];c;c=c.yb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.gb.lookup(a,b)}
function Mb(a,b,c,d){Zb||(Zb=function(a,b,c,d){a||(a=this);this.parent=a;this.ob=a.ob;this.xb=null;this.id=Rb++;this.name=b;this.mode=c;this.gb={};this.jb={};this.rdev=d},Zb.prototype={},Object.defineProperties(Zb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}}));a=new Zb(a,b,c,d);Wb(a);return a}
function N(a){return 16384===(a&61440)}var $b={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function ac(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Yb(a,b){if(Sb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 13}else return 13;return 0}function bc(a,b){try{return O(a,b),17}catch(c){}return Yb(a,"wx")}
function rc(a,b,c){try{var d=O(a,b)}catch(e){return e.ib}if(a=Yb(a,"wx"))return a;if(c){if(!N(d.mode))return 20;if(d===d.parent||"/"===Ub(d))return 16}else if(N(d.mode))return 21;return 0}function Cc(a){var b=4096;for(a=a||0;a<=b;a++)if(!Q[a])return a;throw new L(24);}
function Dc(a,b){Ec||(Ec=function(){},Ec.prototype={},Object.defineProperties(Ec.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var c=new Ec,d;for(d in a)c[d]=a[d];a=c;b=Cc(b);a.fd=b;return Q[b]=a}var Lb={open:function(a){a.jb=Qb[a.node.rdev].jb;a.jb.open&&a.jb.open(a)},ub:function(){throw new L(29);}};function Hb(a,b){Qb[a]={jb:b}}
function Fc(a,b){var c="/"===b,d=!b;if(c&&Pb)throw new L(16);if(!c&&!d){var e=T(b,{$b:!1});b=e.path;e=e.node;if(e.xb)throw new L(16);if(!N(e.mode))throw new L(20);}b={type:a,Qb:{},cc:b,nc:[]};a=a.ob(b);a.ob=b;b.root=a;c?Pb=a:e&&(e.xb=b,e.ob&&e.ob.nc.push(b))}function ka(a,b,c){var d=T(a,{parent:!0}).node;a=Cb(a);if(!a||"."===a||".."===a)throw new L(22);var e=bc(d,a);if(e)throw new L(e);if(!d.gb.Ab)throw new L(1);return d.gb.Ab(d,a,b,c)}function U(a,b){ka(a,(void 0!==b?b:511)&1023|16384,0)}
function Gc(a,b,c){"undefined"===typeof c&&(c=b,b=438);ka(a,b|8192,c)}function Hc(a,b){if(!Eb(a))throw new L(2);var c=T(b,{parent:!0}).node;if(!c)throw new L(2);b=Cb(b);var d=bc(c,b);if(d)throw new L(d);if(!c.gb.symlink)throw new L(1);c.gb.symlink(c,b,a)}
function ya(a){var b=T(a,{parent:!0}).node,c=Cb(a),d=O(b,c),e=rc(b,c,!1);if(e)throw new L(e);if(!b.gb.unlink)throw new L(1);if(d.xb)throw new L(16);try{S.willDeletePath&&S.willDeletePath(a)}catch(g){console.log("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+g.message)}b.gb.unlink(b,c);Xb(d);try{if(S.onDeletePath)S.onDeletePath(a)}catch(g){console.log("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+g.message)}}
function Tb(a){a=T(a).node;if(!a)throw new L(2);if(!a.gb.readlink)throw new L(22);return Eb(Ub(a.parent),a.gb.readlink(a))}function wa(a,b){a=T(a,{wb:!b}).node;if(!a)throw new L(2);if(!a.gb.qb)throw new L(1);return a.gb.qb(a)}function Ic(a){return wa(a,!0)}function la(a,b){var c;"string"===typeof a?c=T(a,{wb:!0}).node:c=a;if(!c.gb.mb)throw new L(1);c.gb.mb(c,{mode:b&4095|c.mode&-4096,timestamp:Date.now()})}
function Jc(a){var b;"string"===typeof a?b=T(a,{wb:!0}).node:b=a;if(!b.gb.mb)throw new L(1);b.gb.mb(b,{timestamp:Date.now()})}function Kc(a,b){if(0>b)throw new L(22);var c;"string"===typeof a?c=T(a,{wb:!0}).node:c=a;if(!c.gb.mb)throw new L(1);if(N(c.mode))throw new L(21);if(32768!==(c.mode&61440))throw new L(22);if(a=Yb(c,"w"))throw new L(a);c.gb.mb(c,{size:b,timestamp:Date.now()})}
function p(a,b,c,d){if(""===a)throw new L(2);if("string"===typeof b){var e=$b[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=Ab(a);try{g=T(a,{wb:!(b&131072)}).node}catch(k){}}e=!1;if(b&64)if(g){if(b&128)throw new L(17);}else g=ka(a,c,0),e=!0;if(!g)throw new L(2);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&!N(g.mode))throw new L(20);if(!e&&(c=g?40960===(g.mode&61440)?40:N(g.mode)&&
("r"!==ac(b)||b&512)?21:Yb(g,ac(b)):2))throw new L(c);b&512&&Kc(g,0);b&=-641;d=Dc({node:g,path:Ub(g),flags:b,seekable:!0,position:0,jb:g.jb,uc:[],error:!1},d);d.jb.open&&d.jb.open(d);!l.logReadFiles||b&1||(Lc||(Lc={}),a in Lc||(Lc[a]=1,console.log("FS.trackingDelegate error on read file: "+a)));try{S.onOpenFile&&(g=0,1!==(b&2097155)&&(g|=1),0!==(b&2097155)&&(g|=2),S.onOpenFile(a,g))}catch(k){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+k.message)}return d}
function na(a){if(null===a.fd)throw new L(9);a.Mb&&(a.Mb=null);try{a.jb.close&&a.jb.close(a)}catch(b){throw b;}finally{Q[a.fd]=null}a.fd=null}function Mc(a,b,c){if(null===a.fd)throw new L(9);if(!a.seekable||!a.jb.ub)throw new L(29);if(0!=c&&1!=c&&2!=c)throw new L(22);a.position=a.jb.ub(a,b,c);a.uc=[]}
function xa(a,b,c,d,e){if(0>d||0>e)throw new L(22);if(null===a.fd)throw new L(9);if(1===(a.flags&2097155))throw new L(9);if(N(a.node.mode))throw new L(21);if(!a.jb.read)throw new L(22);var g="undefined"!==typeof e;if(!g)e=a.position;else if(!a.seekable)throw new L(29);b=a.jb.read(a,b,c,d,e);g||(a.position+=b);return b}
function ma(a,b,c,d,e,g){if(0>d||0>e)throw new L(22);if(null===a.fd)throw new L(9);if(0===(a.flags&2097155))throw new L(9);if(N(a.node.mode))throw new L(21);if(!a.jb.write)throw new L(22);a.flags&1024&&Mc(a,0,2);var k="undefined"!==typeof e;if(!k)e=a.position;else if(!a.seekable)throw new L(29);b=a.jb.write(a,b,c,d,e,g);k||(a.position+=b);try{if(a.path&&S.onWriteToFile)S.onWriteToFile(a.path)}catch(m){console.log("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+m.message)}return b}
function Nc(){L||(L=function(a,b){this.node=b;this.sc=function(a){this.ib=a};this.sc(a);this.message="FS error";this.stack&&Object.defineProperty(this,"stack",{value:Error().stack,writable:!0})},L.prototype=Error(),L.prototype.constructor=L,[2].forEach(function(a){Nb[a]=new L(a);Nb[a].stack="<generic error, no stack>"}))}var Oc;function ja(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Pc(a,b,c){a=n("/dev",a);var d=ja(!!b,!!c);Qc||(Qc=64);var e=Qc++<<8|0;Hb(e,{open:function(a){a.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(a,c,d,e){for(var g=0,k=0;k<e;k++){try{var m=b()}catch(Na){throw new L(5);}if(void 0===m&&0===g)throw new L(11);if(null===m||void 0===m)break;g++;c[d+k]=m}g&&(a.node.timestamp=Date.now());return g},write:function(a,b,d,e){for(var g=0;g<e;g++)try{c(b[d+g])}catch(da){throw new L(5);}e&&(a.node.timestamp=Date.now());return g}});
Gc(a,d,e)}var Qc,V={},Zb,Ec,Lc,Rc={};
function Sc(a,b,c){try{var d=a(b)}catch(e){if(e&&e.node&&Ab(b)!==Ab(Ub(e.node)))return-20;throw e;}E[c>>2]=d.dev;E[c+4>>2]=0;E[c+8>>2]=d.ino;E[c+12>>2]=d.mode;E[c+16>>2]=d.nlink;E[c+20>>2]=d.uid;E[c+24>>2]=d.gid;E[c+28>>2]=d.rdev;E[c+32>>2]=0;f=[d.size>>>0,(h=d.size,1<=+Wa(h)?0<h?(Xa(+Ya(h/4294967296),4294967295)|0)>>>0:~~+Za((h-+(~~h>>>0))/4294967296)>>>0:0)];E[c+40>>2]=f[0];E[c+44>>2]=f[1];E[c+48>>2]=4096;E[c+52>>2]=d.blocks;E[c+56>>2]=d.atime.getTime()/1E3|0;E[c+60>>2]=0;E[c+64>>2]=d.mtime.getTime()/
1E3|0;E[c+68>>2]=0;E[c+72>>2]=d.ctime.getTime()/1E3|0;E[c+76>>2]=0;f=[d.ino>>>0,(h=d.ino,1<=+Wa(h)?0<h?(Xa(+Ya(h/4294967296),4294967295)|0)>>>0:~~+Za((h-+(~~h>>>0))/4294967296)>>>0:0)];E[c+80>>2]=f[0];E[c+84>>2]=f[1];return 0}var W=0;function X(){W+=4;return E[W-4>>2]}function Y(){return H(X())}function Z(){var a=Q[X()];if(!a)throw new L(9);return a}function Ja(){return t.length}
function Tc(a){a=eb(a);var b=buffer.byteLength;try{return-1!==Sa.grow((a-b)/65536)?(buffer=Sa.buffer,!0):!1}catch(c){return!1}}function Ka(a){if(2147418112<a)return!1;for(var b=Math.max(Ja(),16777216);b<a;)536870912>=b?b=eb(2*b):b=Math.min(eb((3*b+2147483648)/4),2147418112);if(!Tc(b))return!1;fb();return!0}function Uc(a){if(0===a)return 0;a=H(a);if(!K.hasOwnProperty(a))return 0;Uc.fb&&qa(Uc.fb);a=K[a];var b=ta(a)+1,c=bb(b);c&&u(a,t,c,b);Uc.fb=c;return Uc.fb}u("GMT",G,60704,4);
function Vc(){function a(a){return(a=a.toTimeString().match(/\(([A-Za-z ]+)\)$/))?a[1]:"GMT"}if(!Wc){Wc=!0;E[Xc()>>2]=60*(new Date).getTimezoneOffset();var b=new Date(2E3,0,1),c=new Date(2E3,6,1);E[Yc()>>2]=Number(b.getTimezoneOffset()!=c.getTimezoneOffset());var d=a(b),e=a(c);d=pa(oa(d));e=pa(oa(e));c.getTimezoneOffset()<b.getTimezoneOffset()?(E[Zc()>>2]=d,E[Zc()+4>>2]=e):(E[Zc()>>2]=e,E[Zc()+4>>2]=d)}}var Wc;
function $c(a){a/=1E3;if((Ca||z)&&self.performance&&self.performance.now)for(var b=self.performance.now();self.performance.now()-b<a;);else for(b=Date.now();Date.now()-b<a;);return 0}l._usleep=$c;Nc();R=Array(4096);Fc(M,"/");U("/tmp");U("/home");U("/home/web_user");
(function(){U("/dev");Hb(259,{read:function(){return 0},write:function(a,b,c,k){return k}});Gc("/dev/null",259);Gb(1280,Jb);Gb(1536,Kb);Gc("/dev/tty",1280);Gc("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(A)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){C("random_device")});Pc("random",b);Pc("urandom",b);U("/dev/shm");
U("/dev/shm/tmp")})();U("/proc");U("/proc/self");U("/proc/self/fd");Fc({ob:function(){var a=Mb("/proc/self","fd",16895,73);a.gb={lookup:function(a,c){var b=Q[+c];if(!b)throw new L(9);a={parent:null,ob:{cc:"fake"},gb:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");if(A){var fs=require("fs"),Ob=require("path");P.tc()}function oa(a,b){var c=Array(ta(a)+1);a=u(a,c,0,c.length);b&&(c.length=a);return c}
var cd=l.asm({},{n:C,B:function(){return 0},l:function(a){return F[a]()},i:function(a,b){return F[a](b)},h:function(a,b,c){return F[a](b,c)},g:function(a,b,c,d){return F[a](b,c,d)},f:function(a,b,c,d,e){return F[a](b,c,d,e)},e:function(a,b,c,d,e,g){return F[a](b,c,d,e,g)},d:function(a,b,c,d,e,g,k){return F[a](b,c,d,e,g,k)},G:function(a,b,c,d,e,g,k){return F[a](b,c,d,e,g,k)},F:function(a,b,c,d,e){return F[a](b,c,d,e)},E:function(a,b,c){return F[a](b,c)},D:function(a,b,c,d){return F[a](b,c,d)},C:function(a,
b,c,d,e){return F[a](b,c,d,e)},A:function(a,b,c,d){return F[a](b,c,d)},c:function(a,b){F[a](b)},b:function(a,b,c){F[a](b,c)},k:function(a,b,c,d){F[a](b,c,d)},j:function(a,b,c,d,e){F[a](b,c,d,e)},z:function(a,b,c,d,e,g){F[a](b,c,d,e,g)},y:function(a,b,c,d){F[a](b,c,d)},x:function(a,b,c,d){F[a](b,c,d)},m:function(a,b,c,d){C("Assertion failed: "+H(a)+", at: "+[b?H(b):"unknown filename",c,d?H(d):"unknown function"])},la:xb,w:yb,ka:function(a,b){W=b;try{var c=Y();ya(c);return 0}catch(d){return"undefined"!==
typeof V&&d instanceof L||C(d),-d.ib}},ja:function(a,b){W=b;try{return Z(),0}catch(c){return"undefined"!==typeof V&&c instanceof L||C(c),-c.ib}},v:function(a,b){W=b;try{var c=Z(),d=X(),e=X(),g=X(),k=X();if(!(-1==d&&0>e||0==d&&0<=e))return-75;Mc(c,e,k);f=[c.position>>>0,(h=c.position,1<=+Wa(h)?0<h?(Xa(+Ya(h/4294967296),4294967295)|0)>>>0:~~+Za((h-+(~~h>>>0))/4294967296)>>>0:0)];E[g>>2]=f[0];E[g+4>>2]=f[1];c.Mb&&0===e&&0===k&&(c.Mb=null);return 0}catch(m){return"undefined"!==typeof V&&m instanceof L||
C(m),-m.ib}},u:function(a,b){W=b;try{var c=Z(),d=X();a:{var e=X();for(b=a=0;b<e;b++){var g=ma(c,t,E[d+8*b>>2],E[d+(8*b+4)>>2],void 0);if(0>g){var k=-1;break a}a+=g}k=a}return k}catch(m){return"undefined"!==typeof V&&m instanceof L||C(m),-m.ib}},ia:function(a,b){W=b;try{var c=Y(),d=X();la(c,d);return 0}catch(e){return"undefined"!==typeof V&&e instanceof L||C(e),-e.ib}},ha:function(a,b){W=b;try{var c=X(),d=X();if(0===d)return-22;if(d<ta("/")+1)return-34;u("/",G,c,d);return c}catch(e){return"undefined"!==
typeof V&&e instanceof L||C(e),-e.ib}},ga:function(a,b){W=b;try{var c=X(),d=X(),e=X(),g=X(),k=X(),m=X();m<<=12;a=!1;if(-1===k){var x=ad(16384,d);if(!x)return-12;bd(x,0,d);a=!0}else{var y=Q[k];if(!y)return-9;b=G;if(1===(y.flags&2097155))throw new L(13);if(!y.jb.Hb)throw new L(19);var da=y.jb.Hb(y,b,c,d,m,e,g);x=da.oc;a=da.Kb}Rc[x]={mc:x,lc:d,Kb:a,fd:k,flags:g};return x}catch(ea){return"undefined"!==typeof V&&ea instanceof L||C(ea),-ea.ib}},fa:function(a,b){W=b;try{var c=X();X();var d=X();X();var e=
Q[c];if(!e)throw new L(9);if(0===(e.flags&2097155))throw new L(22);Kc(e.node,d);return 0}catch(g){return"undefined"!==typeof V&&g instanceof L||C(g),-g.ib}},t:function(a,b){W=b;try{var c=Y(),d=X();return Sc(wa,c,d)}catch(e){return"undefined"!==typeof V&&e instanceof L||C(e),-e.ib}},ea:function(a,b){W=b;try{var c=Y(),d=X();return Sc(Ic,c,d)}catch(e){return"undefined"!==typeof V&&e instanceof L||C(e),-e.ib}},da:function(a,b){W=b;try{var c=Z(),d=X();return Sc(wa,c.path,d)}catch(e){return"undefined"!==
typeof V&&e instanceof L||C(e),-e.ib}},ca:function(a,b){W=b;return 42},ba:function(a,b){W=b;return 0},aa:function(a,b){W=b;try{var c=X();X();X();var d=Q[c];if(!d)throw new L(9);Jc(d.node);return 0}catch(e){return"undefined"!==typeof V&&e instanceof L||C(e),-e.ib}},$:function(a,b){W=b;try{var c=Y();X();X();Jc(c);return 0}catch(d){return"undefined"!==typeof V&&d instanceof L||C(d),-d.ib}},o:function(a,b){W=b;try{var c=Z();switch(X()){case 0:var d=X();return 0>d?-22:p(c.path,c.flags,0,d).fd;case 1:case 2:return 0;
case 3:return c.flags;case 4:return d=X(),c.flags|=d,0;case 12:return d=X(),Pa[d+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-22;case 9:return yb(22),-1;default:return-22}}catch(e){return"undefined"!==typeof V&&e instanceof L||C(e),-e.ib}},_:function(a,b){W=b;try{var c=Z(),d=X(),e=X();return xa(c,t,d,e)}catch(g){return"undefined"!==typeof V&&g instanceof L||C(g),-g.ib}},Z:function(a,b){W=b;try{var c=Y();var d=X();if(d&-8)var e=-22;else{var g=T(c,{wb:!0}).node;a="";d&4&&(a+="r");d&2&&(a+=
"w");d&1&&(a+="x");e=a&&Yb(g,a)?-13:0}return e}catch(k){return"undefined"!==typeof V&&k instanceof L||C(k),-k.ib}},Y:function(a,b){W=b;try{var c=Y(),d=X();a=c;a=Ab(a);"/"===a[a.length-1]&&(a=a.substr(0,a.length-1));U(a,d);return 0}catch(e){return"undefined"!==typeof V&&e instanceof L||C(e),-e.ib}},X:function(a,b){W=b;try{var c=Z(),d=X(),e=X();return ma(c,t,d,e)}catch(g){return"undefined"!==typeof V&&g instanceof L||C(g),-g.ib}},W:function(a,b){W=b;try{var c=Y(),d=T(c,{parent:!0}).node,e=Cb(c),g=O(d,
e),k=rc(d,e,!0);if(k)throw new L(k);if(!d.gb.rmdir)throw new L(1);if(g.xb)throw new L(16);try{S.willDeletePath&&S.willDeletePath(c)}catch(m){console.log("FS.trackingDelegate['willDeletePath']('"+c+"') threw an exception: "+m.message)}d.gb.rmdir(d,e);Xb(g);try{if(S.onDeletePath)S.onDeletePath(c)}catch(m){console.log("FS.trackingDelegate['onDeletePath']('"+c+"') threw an exception: "+m.message)}return 0}catch(m){return"undefined"!==typeof V&&m instanceof L||C(m),-m.ib}},V:function(a,b){W=b;try{var c=
Y(),d=X(),e=X();return p(c,d,e).fd}catch(g){return"undefined"!==typeof V&&g instanceof L||C(g),-g.ib}},p:function(a,b){W=b;try{var c=Z();na(c);return 0}catch(d){return"undefined"!==typeof V&&d instanceof L||C(d),-d.ib}},U:function(a,b){W=b;try{var c=Y(),d=X();var e=X();if(0>=e)var g=-22;else{var k=Tb(c),m=Math.min(e,ta(k)),x=t[d+m];u(k,G,d,e+1);t[d+m]=x;g=m}return g}catch(y){return"undefined"!==typeof V&&y instanceof L||C(y),-y.ib}},T:function(a,b){W=b;try{var c=X(),d=X(),e=Rc[c];if(!e)return 0;if(d===
e.lc){var g=Q[e.fd],k=e.flags,m=new Uint8Array(G.subarray(c,c+d));g&&g.jb.Ib&&g.jb.Ib(g,m,0,d,k);Rc[c]=null;e.Kb&&qa(e.mc)}return 0}catch(x){return"undefined"!==typeof V&&x instanceof L||C(x),-x.ib}},S:function(a,b){W=b;try{var c=X(),d=X(),e=Q[c];if(!e)throw new L(9);la(e.node,d);return 0}catch(g){return"undefined"!==typeof V&&g instanceof L||C(g),-g.ib}},R:function(){l.abort()},Q:Ja,P:function(a,b,c){G.set(G.subarray(b,b+c),a)},O:Ka,s:Uc,r:function(a){var b=Date.now();E[a>>2]=b/1E3|0;E[a+4>>2]=b%
1E3*1E3|0;return 0},N:function(a){return Math.log(a)/Math.LN10},q:function(){C("trap!")},M:function(a){Vc();a=new Date(1E3*E[a>>2]);E[15164]=a.getSeconds();E[15165]=a.getMinutes();E[15166]=a.getHours();E[15167]=a.getDate();E[15168]=a.getMonth();E[15169]=a.getFullYear()-1900;E[15170]=a.getDay();var b=new Date(a.getFullYear(),0,1);E[15171]=(a.getTime()-b.getTime())/864E5|0;E[15173]=-(60*a.getTimezoneOffset());var c=(new Date(2E3,6,1)).getTimezoneOffset();b=b.getTimezoneOffset();a=(c!=b&&a.getTimezoneOffset()==
Math.min(b,c))|0;E[15172]=a;a=E[Zc()+(a?4:0)>>2];E[15174]=a;return 60656},L:function(a,b){var c=E[a>>2];a=E[a+4>>2];0!==b&&(E[b>>2]=0,E[b+4>>2]=0);return $c(1E6*c+a/1E3)},K:function(a){switch(a){case 30:return 16384;case 85:return 131068;case 132:case 133:case 12:case 137:case 138:case 15:case 235:case 16:case 17:case 18:case 19:case 20:case 149:case 13:case 10:case 236:case 153:case 9:case 21:case 22:case 159:case 154:case 14:case 77:case 78:case 139:case 80:case 81:case 82:case 68:case 67:case 164:case 11:case 29:case 47:case 48:case 95:case 52:case 51:case 46:return 200809;
case 79:return 0;case 27:case 246:case 127:case 128:case 23:case 24:case 160:case 161:case 181:case 182:case 242:case 183:case 184:case 243:case 244:case 245:case 165:case 178:case 179:case 49:case 50:case 168:case 169:case 175:case 170:case 171:case 172:case 97:case 76:case 32:case 173:case 35:return-1;case 176:case 177:case 7:case 155:case 8:case 157:case 125:case 126:case 92:case 93:case 129:case 130:case 131:case 94:case 91:return 1;case 74:case 60:case 69:case 70:case 4:return 1024;case 31:case 42:case 72:return 32;
case 87:case 26:case 33:return 2147483647;case 34:case 1:return 47839;case 38:case 36:return 99;case 43:case 37:return 2048;case 0:return 2097152;case 3:return 65536;case 28:return 32768;case 44:return 32767;case 75:return 16384;case 39:return 1E3;case 89:return 700;case 71:return 256;case 40:return 255;case 2:return 100;case 180:return 64;case 25:return 20;case 5:return 16;case 6:return 6;case 73:return 4;case 84:return"object"===typeof navigator?navigator.hardwareConcurrency||1:1}yb(22);return-1},
J:function(a){var b=Date.now()/1E3|0;a&&(E[a>>2]=b);return b},I:function(a,b){if(b){var c=1E3*E[b+8>>2];c+=E[b+12>>2]/1E3}else c=Date.now();a=H(a);try{b=c;var d=T(a,{wb:!0}).node;d.gb.mb(d,{timestamp:Math.max(b,c)});return 0}catch(e){a=e;if(!(a instanceof L)){a+=" : ";a:{d=Error();if(!d.stack){try{throw Error(0);}catch(g){d=g}if(!d.stack){d="(no stack trace available)";break a}}d=d.stack.toString()}l.extraStackTrace&&(d+="\n"+l.extraStackTrace());d=db(d);throw a+d;}yb(a.ib);return-1}},H:function(){C("OOM")},
a:Ia},buffer);l.asm=cd;l._RegisterExtensionFunctions=function(){return l.asm.ma.apply(null,arguments)};var wb=l.___emscripten_environ_constructor=function(){return l.asm.na.apply(null,arguments)};l.___errno_location=function(){return l.asm.oa.apply(null,arguments)};
var Yc=l.__get_daylight=function(){return l.asm.pa.apply(null,arguments)},Xc=l.__get_timezone=function(){return l.asm.qa.apply(null,arguments)},Zc=l.__get_tzname=function(){return l.asm.ra.apply(null,arguments)},qa=l._free=function(){return l.asm.sa.apply(null,arguments)},bb=l._malloc=function(){return l.asm.ta.apply(null,arguments)},ad=l._memalign=function(){return l.asm.ua.apply(null,arguments)},bd=l._memset=function(){return l.asm.va.apply(null,arguments)};
l._sqlite3_bind_blob=function(){return l.asm.wa.apply(null,arguments)};l._sqlite3_bind_double=function(){return l.asm.xa.apply(null,arguments)};l._sqlite3_bind_int=function(){return l.asm.ya.apply(null,arguments)};l._sqlite3_bind_parameter_index=function(){return l.asm.za.apply(null,arguments)};l._sqlite3_bind_text=function(){return l.asm.Aa.apply(null,arguments)};l._sqlite3_changes=function(){return l.asm.Ba.apply(null,arguments)};l._sqlite3_clear_bindings=function(){return l.asm.Ca.apply(null,arguments)};
l._sqlite3_close_v2=function(){return l.asm.Da.apply(null,arguments)};l._sqlite3_column_blob=function(){return l.asm.Ea.apply(null,arguments)};l._sqlite3_column_bytes=function(){return l.asm.Fa.apply(null,arguments)};l._sqlite3_column_double=function(){return l.asm.Ga.apply(null,arguments)};l._sqlite3_column_name=function(){return l.asm.Ha.apply(null,arguments)};l._sqlite3_column_text=function(){return l.asm.Ia.apply(null,arguments)};l._sqlite3_column_type=function(){return l.asm.Ja.apply(null,arguments)};
l._sqlite3_create_function_v2=function(){return l.asm.Ka.apply(null,arguments)};l._sqlite3_data_count=function(){return l.asm.La.apply(null,arguments)};l._sqlite3_errmsg=function(){return l.asm.Ma.apply(null,arguments)};l._sqlite3_exec=function(){return l.asm.Na.apply(null,arguments)};l._sqlite3_finalize=function(){return l.asm.Oa.apply(null,arguments)};l._sqlite3_free=function(){return l.asm.Pa.apply(null,arguments)};l._sqlite3_open=function(){return l.asm.Qa.apply(null,arguments)};
l._sqlite3_prepare_v2=function(){return l.asm.Ra.apply(null,arguments)};l._sqlite3_reset=function(){return l.asm.Sa.apply(null,arguments)};l._sqlite3_result_double=function(){return l.asm.Ta.apply(null,arguments)};l._sqlite3_result_null=function(){return l.asm.Ua.apply(null,arguments)};l._sqlite3_result_text=function(){return l.asm.Va.apply(null,arguments)};l._sqlite3_step=function(){return l.asm.Wa.apply(null,arguments)};l._sqlite3_value_blob=function(){return l.asm.Xa.apply(null,arguments)};
l._sqlite3_value_bytes=function(){return l.asm.Ya.apply(null,arguments)};l._sqlite3_value_double=function(){return l.asm.Za.apply(null,arguments)};l._sqlite3_value_int=function(){return l.asm._a.apply(null,arguments)};l._sqlite3_value_text=function(){return l.asm.$a.apply(null,arguments)};l._sqlite3_value_type=function(){return l.asm.ab.apply(null,arguments)};
var r=l.stackAlloc=function(){return l.asm.cb.apply(null,arguments)},va=l.stackRestore=function(){return l.asm.db.apply(null,arguments)},sa=l.stackSave=function(){return l.asm.eb.apply(null,arguments)};l.dynCall_vi=function(){return l.asm.bb.apply(null,arguments)};l.asm=cd;l.cwrap=function(a,b,c,d){c=c||[];var e=c.every(function(a){return"number"===a});return"string"!==b&&e&&!d?Ua(a):function(){return Va(a,b,c,arguments)}};l.stackSave=sa;l.stackRestore=va;l.stackAlloc=r;
function dd(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}dd.prototype=Error();dd.prototype.constructor=dd;pb=function ed(){l.calledRun||fd();l.calledRun||(pb=ed)};
function fd(){function a(){if(!l.calledRun&&(l.calledRun=!0,!Ta)){mb||(mb=!0,l.noFSInit||Oc||(Oc=!0,Nc(),l.stdin=l.stdin,l.stdout=l.stdout,l.stderr=l.stderr,l.stdin?Pc("stdin",l.stdin):Hc("/dev/tty","/dev/stdin"),l.stdout?Pc("stdout",null,l.stdout):Hc("/dev/tty","/dev/stdout"),l.stderr?Pc("stderr",null,l.stderr):Hc("/dev/tty1","/dev/stderr"),p("/dev/stdin","r"),p("/dev/stdout","w"),p("/dev/stderr","w")),hb(jb));Sb=!1;hb(kb);if(l.onRuntimeInitialized)l.onRuntimeInitialized();if(l.postRun)for("function"==
typeof l.postRun&&(l.postRun=[l.postRun]);l.postRun.length;){var a=l.postRun.shift();lb.unshift(a)}hb(lb)}}if(!(0<I)){if(l.preRun)for("function"==typeof l.preRun&&(l.preRun=[l.preRun]);l.preRun.length;)nb();hb(ib);0<I||l.calledRun||(l.setStatus?(l.setStatus("Running..."),setTimeout(function(){setTimeout(function(){l.setStatus("")},1);a()},1)):a())}}l.run=fd;
function C(a){if(l.onAbort)l.onAbort(a);void 0!==a?(Ga(a),D(a),a=JSON.stringify(a)):a="";Ta=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}l.abort=C;if(l.preInit)for("function"==typeof l.preInit&&(l.preInit=[l.preInit]);0<l.preInit.length;)l.preInit.pop()();l.noExitRuntime=!0;fd();


        // The shell-pre.js and emcc-generated code goes above
        return Module;
    }); // The end of the promise being returned

  return initSqlJsPromise;
} // The end of our initSqlJs function

// This bit below is copied almost exactly from what you get when you use the MODULARIZE=1 flag with emcc
// However, we don't want to use the emcc modularization. See shell-pre.js
if (typeof exports === 'object' && typeof module === 'object'){
    module.exports = initSqlJs;
    // This will allow the module to be used in ES6 or CommonJS
    module.exports.default = initSqlJs;
}
else if (typeof define === 'function' && define['amd']) {
    define([], function() { return initSqlJs; });
}
else if (typeof exports === 'object'){
    exports["Module"] = initSqlJs;
}
    
