# Global constants
NULL = 0 # Null pointer

SQLite.OK=0
SQLite.ERROR=1
SQLite.INTERNAL=2
SQLite.PERM=3
SQLite.ABORT=4
SQLite.BUSY=5
SQLite.LOCKED=6
SQLite.NOMEM=7
SQLite.READONLY=8
SQLite.INTERRUPT=9
SQLite.IOERR=10
SQLite.CORRUPT=11
SQLite.NOTFOUND=12
SQLite.FULL=13
SQLite.CANTOPEN=14
SQLite.PROTOCOL=15
SQLite.EMPTY=16
SQLite.SCHEMA=17
SQLite.TOOBIG=18
SQLite.CONSTRAINT=19
SQLite.MISMATCH=20
SQLite.MISUSE=21
SQLite.NOLFS=22
SQLite.AUTH=23
SQLite.FORMAT=24
SQLite.RANGE=25
SQLite.NOTADB=26
SQLite.NOTICE=27
SQLite.WARNING=28
SQLite.ROW=100
SQLite.DONE=101

# Data types
SQLite.INTEGER=1
SQLite.FLOAT=2
SQLite.TEXT=3
SQLite.BLOB=4
SQLite.NULL=5

# Encodings, used for registering functions. 
SQLite.UTF8=1
