on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create a release

jobs:
  build:
    name: Create a release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make
        uses: ./.github/actions/build-sqljs
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - run: cd dist && zip sqljs-wasm.zip sql-wasm.{js,wasm}
      - name: Upload Release Asset (wasm)
        uses: lovasoa/upload-release-asset@851d9cc59fe8113912edffbd8fddaa09470a5ac0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/sqljs-wasm.zip
          asset_name: sqljs-wasm.zip
          asset_label: wasm version, best runtime performance, smaller assets, requires configuration
          asset_content_type: application/zip
      - name: Upload Release Asset (asm)
        uses: lovasoa/upload-release-asset@851d9cc59fe8113912edffbd8fddaa09470a5ac0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/sql-asm.js
          asset_name: sql.js
          asset_label: asm.js version, slower, easy to integrate and compatible with old browsers 
          asset_content_type: text/javascript
      - run: cd dist && zip sqljs-worker-wasm.zip worker.sql-wasm.js sql-wasm.wasm
      - name: Upload Release Asset (worker wasm)
        uses: lovasoa/upload-release-asset@851d9cc59fe8113912edffbd8fddaa09470a5ac0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/sqljs-worker-wasm.zip
          asset_name: sqljs-worker-wasm.zip
          asset_label: webworker wasm version, to be loaded as a web worker
          asset_content_type: application/zip
      - name: Upload Release Asset (worker asm)
        uses: lovasoa/upload-release-asset@851d9cc59fe8113912edffbd8fddaa09470a5ac0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/worker.sql-asm.js
          asset_name: worker.sql-asm.js
          asset_label: webworker asm version, to be loaded as a web worker
          asset_content_type: text/javascript
      - run: cd dist && zip sqljs-all.zip *.{js,wasm}
      - name: Upload Release Asset (all)
        uses: lovasoa/upload-release-asset@851d9cc59fe8113912edffbd8fddaa09470a5ac0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/sqljs-all.zip
          asset_name: sqljs-all.zip
          asset_label: all versions, including non-minified javascript 
          asset_content_type: application/zip
      - name: publish the package to NPM
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
